$=jQuery;var ismobile=navigator.userAgent.match(/(iPad)|(iPhone)|(iPod)|(android)|(webOS)/i),isIE=jQuery.browser.msie,mouseDownBind="mousedown",mouseMoveBind="mousemove",mouseUpBind="mouseup",mouseOverBind="mouseover",mouseOutBind="mouseout",clickBind="click";ismobile&&(mouseDownBind="vmousedown",mouseMoveBind="vmousemove",mouseUpBind="vmouseup",mouseOverBind="vmouseover",mouseOutBind="vmouseout",clickBind="vclick");var easeOptions=["In","Out","InOut"],typeOptions="linear swing jswing Quad Cubic Quart Quint Expo Sine Circ".split(" ");
jQuery.fn.extend({ensureLoad:function(a){return this.each(function(){this.complete||4===this.readyState?a.call(this):"uninitialized"===this.readyState&&0===this.src.indexOf("data:")?($(this).trigger("error"),a.call(this)):($(this).load(a),isIE&&-1==this.src.indexOf("?")&&(this.src=this.src+"?"+(new Date).getTime()))})}});function parseParameter(a){return isNaN(a)?"true"==a||"false"==a?"true"==a?!0:!1:a:parseFloat(a,10)}function getTween(a,c){return"linear"==c||"swing"==c||"jswing"==c?c:a+c}
function getTransition(a,c,b){a=getTween(a,c);b="all "+b+"s ";switch(a){case "linear":return b+"cubic-bezier(0.250, 0.250, 0.750, 0.750)";case "easeInQuad":return b+"cubic-bezier(0.550, 0.085, 0.680, 0.530)";case "easeInCubic":return b+"cubic-bezier(0.550, 0.055, 0.675, 0.190)";case "easeInQuart":return b+"cubic-bezier(0.895, 0.030, 0.685, 0.220)";case "easeInQuint":return b+"cubic-bezier(0.755, 0.050, 0.855, 0.060)";case "easeInSine":return b+"cubic-bezier(0.470, 0.000, 0.745, 0.715)";case "easeInExpo":return b+
"cubic-bezier(0.950, 0.050, 0.795, 0.035)";case "easeInCirc":return b+"cubic-bezier(0.600, 0.040, 0.980, 0.335)";case "easeOutQuad":return b+"cubic-bezier(0.250, 0.460, 0.450, 0.940)";case "easeOutCubic":return b+"cubic-bezier(0.215, 0.610, 0.355, 1.000)";case "easeOutQuart":return b+"cubic-bezier(0.165, 0.840, 0.440, 1.000)";case "easeOutQuint":return b+"cubic-bezier(0.230, 1.000, 0.320, 1.000)";case "easeOutSine":return b+"cubic-bezier(0.390, 0.575, 0.565, 1.000)";case "easeOutExpo":return b+"cubic-bezier(0.190, 1.000, 0.220, 1.000)";
case "easeOutCirc":return b+"cubic-bezier(0.075, 0.820, 0.165, 1.000)";case "easeInOutQuad":return b+"cubic-bezier(0.455, 0.030, 0.515, 0.955)";case "easeInOutCubic":return b+"cubic-bezier(0.645, 0.045, 0.355, 1.000)";case "easeInOutQuart":return b+"cubic-bezier(0.770, 0.000, 0.175, 1.000)";case "easeInOutQuint":return b+"cubic-bezier(0.860, 0.000, 0.070, 1.000)";case "easeInOutSine":return b+"cubic-bezier(0.445, 0.050, 0.550, 0.950)";case "easeInOutExpo":return b+"cubic-bezier(1.000, 0.000, 0.000, 1.000)";
case "easeInOutCirc":return b+"cubic-bezier(0.785, 0.135, 0.150, 0.860)"}return a}function preventDragDefault(a){isIE&&(a.get(0).onselectstart=function(){return!1});a.get(0).onmousedown=function(a){a.preventDefault()};a.click(function(a){return!1})}jQuery.fn.preventDragDefault=function(){isIE&&($(this).get(0).onselectstart=function(){return!1});$(this).get(0).onmousedown=function(a){a.preventDefault()};$(this).click(function(a){return!1})};
function getClearText(a){return a.replace(/<[^<|>]+?>/gi,"")}function unbindMoveAndUp(){$(document).unbind(mouseMoveBind);$(document).unbind(mouseUpBind)}function addIfDoesnExist(a,c){for(var b=0;b<c.length;b++)if(c[b]==a)return;c.push(a)}function is_string(a){return"string"==typeof a}var split;
split=split||function(a){var c=String.prototype.split,b=/()??/.exec("")[1]===a,d;d=function(d,e,g){if("[object RegExp]"!==Object.prototype.toString.call(e))return c.call(d,e,g);var h=[],k=(e.ignoreCase?"i":"")+(e.multiline?"m":"")+(e.extended?"x":"")+(e.sticky?"y":""),m=0;e=RegExp(e.source,k+"g");var n,l,p;d+="";b||(n=RegExp("^"+e.source+"$(?!\\s)",k));for(g=g===a?4294967295:g>>>0;l=e.exec(d);){k=l.index+l[0].length;if(k>m&&(h.push(d.slice(m,l.index)),!b&&1<l.length&&l[0].replace(n,function(){for(var b=
1;b<arguments.length-2;b++)arguments[b]===a&&(l[b]=a)}),1<l.length&&l.index<d.length&&Array.prototype.push.apply(h,l.slice(1)),p=l[0].length,m=k,h.length>=g))break;e.lastIndex===l.index&&e.lastIndex++}m===d.length?!p&&e.test("")||h.push(""):h.push(d.slice(m));return h.length>g?h.slice(0,g):h};String.prototype.split=function(a,b){return d(this,a,b)};return d}();
function stringToObject(a){if(null!=a&&void 0!=a){a=split(a,"; ");var c={};$.each(a,function(a,d){var f=split(d,/:(.+)?/);c[f[0]]=f[1]});return c}return{}}jQuery.fn.swapWith=function(a){return this.each(function(){var c=$(a).clone(!0),b=$(this).clone(!0);$(a).replaceWith(b);$(this).replaceWith(c)})};function removePositionInArray(a,c){for(var b=[],d=0;d<a.length;d++)d!=c&&b.push(a[d]);return b}
jQuery.fn.addRoundCorners=function(a){$(this).css({"-webkit-border-radius":a,"-moz-border-radius":a,"-o-border-radius":a,"border-radius":a})};jQuery.fn.setTransformOrigin=function(a,c){$(this).css({"transform-origin":a+"% "+c+"%","-ms-transform-origin":a+"% "+c+"%","-webkit-transform-origin":a+"% "+c+"%","-moz-transform-origin":a+"% "+c+"%","-o-transform-origin":a+"% "+c+"%"});return this};
jQuery.fn.setTransform=function(a){$(this).css({transform:a,"-ms-transform":a,"-webkit-transform":a,"-moz-transform":a,"-o-transform":a});return this};jQuery.fn.setTransition=function(a){$(this).css({"-webkit-transition":a,"-moz-transition":a,"-ms-transition":a,"-o-transition":a,transition:a});return this};
jQuery.fn.setIETransform=function(a){var c=1,b=1,d=0,f=0;void 0!=a.scale&&(c*=a.scale,b*=a.scale);void 0!=a.translateX&&(d=a.translateX);void 0!=a.translateY&&(f=a.translateY);$(this).css({filter:'progid:DXImageTransform.Microsoft.Matrix(FilterType="nearest neighbor",M11='+c+",M12=0,M21=0,M22="+b+",Dx="+d+",Dy="+f+")"});return this};
jQuery.fn.changeOpacity=function(a){$(this).css({"-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity="+a+")",filter:"alpha(opacity="+a+")","-moz-opacity":a/100,"-khtml-opacity":a/100,opacity:a/100});return this};function getFilter(a,c){var b=parseInt(255*parseFloat(c,10)).toString(16);return"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+b+a.substring(1,3)+a.substring(3,5)+a.substring(5,7)+",endColorstr=#"+b+a.substring(1,3)+a.substring(3,5)+a.substring(5,7)+")"}
function getRGBA(a,c){var b=hex2rgb(a);return"rgba("+b.red+", "+b.green+", "+b.blue+", "+c+")"}jQuery.fn.processColorAndPattern=function(a,c,b){var d=$(this);if("0"!=c&&0!=c){var f=getFilter(a,c);c=getRGBA(a,c);d.css({"background-color":a,filter:f,background:c})}else d.css({"background-color":"transparent",background:"transparent"});"none"!=b&&void 0!=b&&d.css({"background-image":"url("+b+")","background-repeat":"repeat"})};
jQuery.fn.addEaseAll=function(a,c,b){void 0==c&&(c="ease");void 0==b&&(b=["all"]);var d="",f=!0;$.each(b,function(b,g){f||(d+=", ");f=!1;d+=g+" "+a+"s "+c});$(this).css({transition:d,"-webkit-transition":d,"-moz-transition":d,"-o-transition":d})};jQuery.fn.removeEaseAll=function(){$(this).css({transition:"none","-webkit-transition":"none","-moz-transition":"none","-o-transition":"none"})};function componentToHex(a){a=a.toString(16);return 1==a.length?"0"+a:a}
function rgbToHex(a,c,b){return"#"+componentToHex(a)+componentToHex(c)+componentToHex(b)}function isOnePointZero(a){return"string"==typeof a&&-1!=a.indexOf(".")&&1===parseFloat(a)}function isPercentage(a){return"string"===typeof a&&-1!=a.indexOf("%")}function bound01(a,c){isOnePointZero(a)&&(a="100%");var b=isPercentage(a);a=Math.min(c,Math.max(0,parseFloat(a)));b&&(a=parseInt(a*c,10)/100);return 1E-6>Math.abs(a-c)?1:a%c/parseFloat(c)}
function hsvToRgb(a,c,b){a=6*bound01(a,360);c=bound01(c,100);b=bound01(b,100);var d=Math.floor(a),f=a-d;a=b*(1-c);var e=b*(1-f*c);c=b*(1-(1-f)*c);d%=6;return{r:255*[b,e,a,a,c,b][d],g:255*[c,b,b,e,a,a][d],b:255*[a,a,c,b,b,e][d]}}
function hex2rgb(a){if(3>a.length||7<a.length)return{red:0,green:0,blue:0};"#"==a.charAt(0)&&(a=a.substr(1));if(3==a.length){var c=a;a="";for(var c=/^([a-f0-9])([a-f0-9])([a-f0-9])$/i.exec(c).slice(1),b=0;3>b;b++)a+=c[b]+c[b]}a=/^([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})$/i.exec(a).slice(1);return{red:parseInt(a[0],16),green:parseInt(a[1],16),blue:parseInt(a[2],16)}}
function rgbToHsv(a,c,b){a=bound01(a,255);c=bound01(c,255);b=bound01(b,255);var d=Math.max(a,c,b),f=Math.min(a,c,b),e,g=d-f;if(d==f)e=0;else{switch(d){case a:e=(c-b)/g+(c<b?6:0);break;case c:e=(b-a)/g+2;break;case b:e=(a-c)/g+4}e/=6}return{h:e,s:0===d?0:g/d,v:d}}
jQuery.fn.resizeAndCenter=function(a,c,b,d,f){var e=$(this).width(),g=$(this).height();void 0==f&&(f="normal");void 0!=b&&(e=b);void 0!=d&&(g=d);var h=d,k=b;"normal"==f&&(b>a||d>c)&&(f="fit");if("full"==f||"fit"==f)b=g/c,h=g/b,k=e/b;"full"==f&&k<a&&(b=e/a,h=g/b,k=e/b);"fit"==f&&k>a&&(b=e/a,h=g/b,k=e/b);$(this).css({height:h+"px",width:k+"px",top:Math.round(c/2-h/2)+"px",left:Math.round(a/2-k/2)+"px"});return this};
jQuery.fn.processFont=function(a,c,b){$(this).css({"font-family":a,color:c,"font-size":b+"px"})};jQuery.fn.processIcon=function(a){$(this).css({"background-image":"url("+a+")","background-repeat":"no-repeat","background-position":"15px 11px"})};
