define(["jquery","utils/utils","essenza/Shortcodes","jquery/jquery.easing.1.3"],function(d){var e=function(a,c,b){a.attr("rel");this.$obj=a;this.rel=a.attr("rel");this.currentStep=this.ratioShouldBe=this.offScale=this.yratio=this.xratio=1;this.builderHeight=b;this.builderWidth=c;this.parameters={type:this.type,xpos1:0,xpos2:0,xpos3:0,xpos4:0,ypos1:0,ypos2:0,ypos3:0,ypos4:0,opc1:100,opc2:100,opc3:100,opc4:100,size1:100,size2:100,size3:100,size4:100,duration1:0.5,duration2:0.5,duration3:0.5,delay1:0,
delay2:0,delay3:0,ease1:0,ease2:0,ease3:0,type1:0,type2:0,type3:0,iniWidth:0,iniHeight:0,vertical_snapping:"center",horizontal_snapping:"center",min_scale:0,max_scale:999};this.parseProperties();this.minScale=parseFloat(this.parameters.min_scale,10)/100;this.maxScale=parseFloat(this.parameters.max_scale,10)/100;this.isImage="image"==this.parameters.type;this.$obj.css({top:0,left:0,"line-height":"normal"}).addClass("element");this.$obj.css("width",this.parameters.iniWidth+"px");this.$obj.find(">*").css("display",
"block");this.isImage?this.$obj.css("height",this.parameters.iniHeight+"px"):this.parameters.iniHeight=this.$obj.height();"button"==this.parameters.type&&newPqButton.call(this.$obj.find("a").get(0));this.makeAnimationInstances();this.transform();this.$obj.changeOpacity(parseFloat(this["instance"+this.currentStep].opacity,10))};e.prototype={parseProperties:function(){var a=jQuery.parseJSON(this.rel);void 0!=a&&d.each(a,d.proxy(function(a,b){this.parameters.hasOwnProperty(a)&&(this.parameters[a]=b,
this.parameters[a]=parseParameter(this.parameters[a]))},this))},makeAnimationInstances:function(){var a="image"==this.parameters.type;this.instance1={translateX:this.parameters.xpos1,translateY:this.parameters.ypos1,opacity:this.parameters.opc1};this.instance2={translateX:this.parameters.xpos2,translateY:this.parameters.ypos2,opacity:this.parameters.opc2};this.instance3={translateX:this.parameters.xpos3,translateY:this.parameters.ypos3,opacity:this.parameters.opc3};this.instance4={translateX:this.parameters.xpos4,
translateY:this.parameters.ypos4,opacity:this.parameters.opc4};a&&(this.instance1.scale=this.parameters.size1,this.instance2.scale=this.parameters.size2,this.instance3.scale=this.parameters.size3,this.instance4.scale=this.parameters.size4);this.transition0="";this.transition1=getTransition(this.parameters.ease1,this.parameters.type1,this.parameters.duration1);this.transition2=getTransition(this.parameters.ease2,this.parameters.type2,this.parameters.duration2);this.transition3=getTransition(this.parameters.ease3,
this.parameters.type3,this.parameters.duration3)},animateStep:function(){clearTimeout(this.stepTimeout);if(Modernizr.csstransitions)this.$obj.setTransition(this["transition"+this.currentStep]),this.currentStep++,this.transform(),this.$obj.changeOpacity(parseFloat(this["instance"+this.currentStep].opacity,10)),3>this.currentStep&&(this.stepTimeout=setTimeout(d.proxy(this.animateStep,this),(1<this.currentStep?1E3*this.parameters["duration"+(this.currentStep-1)]:0)+1E3*this.parameters["delay"+this.currentStep]));
else if(0==this.currentStep)this.transform(),this.currentStep++,this.$obj.stop().animate({opacity:parseFloat(this["instance"+this.currentStep].opacity,10)/100},1),this.stepTimeout=setTimeout(d.proxy(this.animateStep,this),1E3*this.parameters["delay"+this.currentStep]);else{var a=this.getCurrentStepTransfValues(),c=this["transition"+this.currentStep];this.currentStep++;var b=this.getCurrentStepTransfValues();this.$obj.css("borderSpacing",0);this.$obj.stop();this.$obj.animate({opacity:parseFloat(this["instance"+
this.currentStep].opacity,10)/100},{queue:!1},1);this.$obj.animate({borderSpacing:100},{queue:!1,step:d.proxy(function(c,d){c/=100;this.applyTransform(a.transX+(b.transX-a.transX)*c,a.transY+(b.transY-a.transY)*c,a.scale+(b.scale-a.scale)*c)},this),duration:1<this.currentStep?1E3*this.parameters["duration"+(this.currentStep-1)]:0,complete:d.proxy(function(){3>this.currentStep&&(this.stepTimeout=setTimeout(d.proxy(this.animateStep,this),1E3*this.parameters["delay"+this.currentStep]))},this)},c)}},
getCurrentStepTransfValues:function(){var a=this.isImage?this["instance"+this.currentStep].scale/100:1,c=this["instance"+this.currentStep].translateY,b=this["instance"+this.currentStep].translateX,b=b*this.offScale,c=c*this.offScale,b=b+this.xExtra,c=c+this.yExtra,a=a*this.offScale,b=Math.round(b),c=Math.round(c);return{transX:b,transY:c,scale:a}},transform:function(){if(void 0!=this["instance"+this.currentStep]){var a=this.getCurrentStepTransfValues();this.applyTransform(a.transX,a.transY,a.scale)}},
applyTransform:function(a,c,b){this.isImage&&Modernizr.csstransforms?this.$obj.setTransform("translate("+a+"px,"+c+"px) scale("+b+")"):Modernizr.csstransforms?(this.$obj.setTransform("translate("+a+"px,"+c+"px)"),this.$obj.find(">*").setTransform("scale("+b+")")):(this.$obj.css({top:c+"px",left:a+"px"}),this.isImage?this.$obj.find(">*").css({width:100*b+"%",height:100*b+"%"}):this.$obj.find(">*").css({"-ms-filter":"progid:DXImageTransform.Microsoft.Matrix(sizingMethod='auto expand', M11="+b+", M12=0, M21=0, M22="+
b+")",filter:"progid:DXImageTransform.Microsoft.Matrix(sizingMethod='auto expand', M11="+b+", M12=0, M21=0, M22="+b+")"}))},animateIn:function(){this.currentStep=0;this.animateStep()},animateOut:function(){this.currentStep=3;this.animateStep()},resize:function(a,c){this.width=a;this.height=c;this.xratio=this.width/this.builderWidth;this.yratio=this.height/this.builderHeight;this.offScale=Math.min(this.xratio,this.yratio);this.offScale<this.minScale?this.offScale=this.minScale:this.offScale>this.maxScale&&
(this.offScale=this.maxScale);this.xExtra=this.width-this.builderWidth*this.offScale;this.yExtra=this.height-this.builderHeight*this.offScale;this.xExtra*="left"==this.parameters.horizontal_snapping?0:"center"==this.parameters.horizontal_snapping?0.5:1;this.yExtra*="top"==this.parameters.vertical_snapping?0:"center"==this.parameters.vertical_snapping?0.5:1;-1!=this.currentStep&&(this.currentStep=0,this.animateStep())}};return e});
