var ismobile=navigator.userAgent.match(/(iPad)|(iPhone)|(iPod)|(android)|(webOS)/i),isIE=jQuery.browser.msie,mouseDownBind="mousedown",mouseMoveBind="mousemove",mouseUpBind="mouseup",mouseOverBind="mouseover",mouseOutBind="mouseout",clickBind="click";ismobile&&(mouseDownBind="vmousedown",mouseMoveBind="vmousemove",mouseUpBind="vmouseup",mouseOverBind="vmouseover",mouseOutBind="vmouseout",clickBind="vclick");var easeOptions=["In","Out","InOut"],typeOptions="linear swing jswing Quad Cubic Quart Quint Expo Sine Circ".split(" ");
jQuery.fn.extend({ensureLoad:function(a){return this.each(function(){this.complete||4===this.readyState?a.call(this):"uninitialized"===this.readyState&&0===this.src.indexOf("data:")?($(this).trigger("error"),a.call(this)):($(this).load(a),isIE&&-1==this.src.indexOf("?")&&(this.src=this.src+"?"+(new Date).getTime()))})}});function parseParameter(a){return isNaN(a)?"true"==a||"false"==a?"true"==a?!0:!1:a:parseFloat(a,10)}function getTween(a,c){return"linear"==c||"swing"==c||"jswing"==c?c:a+c}
function getTransition(a,c,b){a=getTween(a,c);b="all "+b+"s ";switch(a){case "linear":return b+"cubic-bezier(0.250, 0.250, 0.750, 0.750)";case "easeInQuad":return b+"cubic-bezier(0.550, 0.085, 0.680, 0.530)";case "easeInCubic":return b+"cubic-bezier(0.550, 0.055, 0.675, 0.190)";case "easeInQuart":return b+"cubic-bezier(0.895, 0.030, 0.685, 0.220)";case "easeInQuint":return b+"cubic-bezier(0.755, 0.050, 0.855, 0.060)";case "easeInSine":return b+"cubic-bezier(0.470, 0.000, 0.745, 0.715)";case "easeInExpo":return b+
"cubic-bezier(0.950, 0.050, 0.795, 0.035)";case "easeInCirc":return b+"cubic-bezier(0.600, 0.040, 0.980, 0.335)";case "easeOutQuad":return b+"cubic-bezier(0.250, 0.460, 0.450, 0.940)";case "easeOutCubic":return b+"cubic-bezier(0.215, 0.610, 0.355, 1.000)";case "easeOutQuart":return b+"cubic-bezier(0.165, 0.840, 0.440, 1.000)";case "easeOutQuint":return b+"cubic-bezier(0.230, 1.000, 0.320, 1.000)";case "easeOutSine":return b+"cubic-bezier(0.390, 0.575, 0.565, 1.000)";case "easeOutExpo":return b+"cubic-bezier(0.190, 1.000, 0.220, 1.000)";
case "easeOutCirc":return b+"cubic-bezier(0.075, 0.820, 0.165, 1.000)";case "easeInOutQuad":return b+"cubic-bezier(0.455, 0.030, 0.515, 0.955)";case "easeInOutCubic":return b+"cubic-bezier(0.645, 0.045, 0.355, 1.000)";case "easeInOutQuart":return b+"cubic-bezier(0.770, 0.000, 0.175, 1.000)";case "easeInOutQuint":return b+"cubic-bezier(0.860, 0.000, 0.070, 1.000)";case "easeInOutSine":return b+"cubic-bezier(0.445, 0.050, 0.550, 0.950)";case "easeInOutExpo":return b+"cubic-bezier(1.000, 0.000, 0.000, 1.000)";
case "easeInOutCirc":return b+"cubic-bezier(0.785, 0.135, 0.150, 0.860)"}return a}function getClearText(a){return a.replace(/<[^<|>]+?>/gi,"")}function unbindMoveAndUp(){$(document).unbind(mouseMoveBind);$(document).unbind(mouseUpBind)}function addIfDoesnExist(a,c){for(var b=0;b<c.length;b++)if(c[b]==a)return;c.push(a)}function is_string(a){return"string"==typeof a}var split;
split=split||function(a){var c=String.prototype.split,b=/()??/.exec("")[1]===a,d;d=function(d,f,h){if("[object RegExp]"!==Object.prototype.toString.call(f))return c.call(d,f,h);var g=[],k=(f.ignoreCase?"i":"")+(f.multiline?"m":"")+(f.extended?"x":"")+(f.sticky?"y":""),m=0;f=RegExp(f.source,k+"g");var n,l,p;d+="";b||(n=RegExp("^"+f.source+"$(?!\\s)",k));for(h=h===a?4294967295:h>>>0;l=f.exec(d);){k=l.index+l[0].length;if(k>m&&(g.push(d.slice(m,l.index)),!b&&1<l.length&&l[0].replace(n,function(){for(var b=
1;b<arguments.length-2;b++)arguments[b]===a&&(l[b]=a)}),1<l.length&&l.index<d.length&&Array.prototype.push.apply(g,l.slice(1)),p=l[0].length,m=k,g.length>=h))break;f.lastIndex===l.index&&f.lastIndex++}m===d.length?!p&&f.test("")||g.push(""):g.push(d.slice(m));return g.length>h?g.slice(0,h):g};String.prototype.split=function(a,b){return d(this,a,b)};return d}();
function stringToObject(a){if(null!=a&&void 0!=a){a=split(a,"; ");var c={};$.each(a,function(a,d){var e=split(d,/:(.+)?/);c[e[0]]=e[1]});return c}return{}}$.fn.swapWith=function(a){return this.each(function(){var c=$(a).clone(!0),b=$(this).clone(!0);$(a).replaceWith(b);$(this).replaceWith(c)})};function removePositionInArray(a,c){for(var b=[],d=0;d<a.length;d++)d!=c&&b.push(a[d]);return b}
$.fn.addRoundCorners=function(a){$(this).css({"-webkit-border-radius":a,"-moz-border-radius":a,"-o-border-radius":a,"border-radius":a})};$.fn.setTransformOrigin=function(a,c){$(this).css({"transform-origin":a+"% "+c+"%","-ms-transform-origin":a+"% "+c+"%","-webkit-transform-origin":a+"% "+c+"%","-moz-transform-origin":a+"% "+c+"%","-o-transform-origin":a+"% "+c+"%"});return this};
$.fn.setTransform=function(a){$(this).css({transform:a,"-ms-transform":a,"-webkit-transform":a,"-moz-transform":a,"-o-transform":a});return this};$.fn.setTransition=function(a){$(this).css({"-webkit-transition":a,"-moz-transition":a,"-ms-transition":a,"-o-transition":a,transition:a});return this};
$.fn.setIETransform=function(a){var c=1,b=1,d=0,e=0;void 0!=a.scale&&(c*=a.scale,b*=a.scale);void 0!=a.translateX&&(d=a.translateX);void 0!=a.translateY&&(e=a.translateY);$(this).css({filter:'progid:DXImageTransform.Microsoft.Matrix(FilterType="nearest neighbor",M11='+c+",M12=0,M21=0,M22="+b+",Dx="+d+",Dy="+e+")"});return this};
$.fn.changeOpacity=function(a){$(this).css({"-ms-filter":"progid:DXImageTransform.Microsoft.Alpha(Opacity="+a+")",filter:"alpha(opacity="+a+")","-moz-opacity":a/100,"-khtml-opacity":a/100,opacity:a/100});return this};function getFilter(a,c){var b=parseInt(255*parseFloat(c,10)).toString(16);return"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+b+a.substring(1,3)+a.substring(3,5)+a.substring(5,7)+",endColorstr=#"+b+a.substring(1,3)+a.substring(3,5)+a.substring(5,7)+")"}
function getRGBA(a,c){var b=hex2rgb(a);return"rgba("+b.red+", "+b.green+", "+b.blue+", "+c+")"}$.fn.processColorAndPattern=function(a,c,b){var d=$(this);if("0"!=c&&0!=c){var e=getFilter(a,c);c=getRGBA(a,c);d.css({"background-color":a,filter:e,background:c})}else d.css({"background-color":"transparent",background:"transparent"});"none"!=b&&void 0!=b&&d.css({"background-image":"url("+b+")","background-repeat":"repeat"})};
$.fn.addEaseAll=function(a,c,b){void 0==c&&(c="ease");void 0==b&&(b=["all"]);var d="",e=!0;$.each(b,function(b,h){e||(d+=", ");e=!1;d+=h+" "+a+"s "+c});$(this).css({transition:d,"-webkit-transition":d,"-moz-transition":d,"-o-transition":d})};$.fn.removeEaseAll=function(){$(this).css({transition:"none","-webkit-transition":"none","-moz-transition":"none","-o-transition":"none"})};function componentToHex(a){a=a.toString(16);return 1==a.length?"0"+a:a}
function rgbToHex(a,c,b){return"#"+componentToHex(a)+componentToHex(c)+componentToHex(b)}
function hsvToRgb(a,c,b){var d,e,f;a=Math.max(0,Math.min(360,a));c=Math.max(0,Math.min(100,c));b=Math.max(0,Math.min(100,b));c/=100;b/=100;if(0==c)return d=c=b,[Math.round(255*d),Math.round(255*c),Math.round(255*b)];a/=60;d=Math.floor(a);e=a-d;a=b*(1-c);f=b*(1-c*e);e=b*(1-c*(1-e));switch(d){case 0:d=b;c=e;b=a;break;case 1:d=f;c=b;b=a;break;case 2:d=a;c=b;b=e;break;case 3:d=a;c=f;break;case 4:d=e;c=a;break;default:d=b,c=a,b=f}return[Math.round(255*d),Math.round(255*c),Math.round(255*b)]}
function hex2rgb(a){if(3>a.length)return{red:0,green:0,blue:0};"#"==a.charAt(0)&&(a=a.substr(1));if(3==a.length){var c=a;a="";for(var c=/^([a-f0-9])([a-f0-9])([a-f0-9])$/i.exec(c).slice(1),b=0;3>b;b++)a+=c[b]+c[b]}a=/^([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})$/i.exec(a).slice(1);return{red:parseInt(a[0],16),green:parseInt(a[1],16),blue:parseInt(a[2],16)}}
function rgbToHsv(a,c,b){a/=255;c/=255;b/=255;var d=Math.max(a,c,b),e=Math.min(a,c,b),f,h=(d+e)/2;if(d==e)f=e=0;else{var g=d-e,e=0.5<h?g/(2-d-e):g/(d+e);switch(d){case a:f=(c-b)/g+(c<b?6:0);break;case c:f=(b-a)/g+2;break;case b:f=(a-c)/g+4}f/=6}return[359*f,100*e,100*h]}
$.fn.resizeAndCenter=function(a,c,b,d,e){var f=$(this).width(),h=$(this).height();void 0==e&&(e="normal");void 0!=b&&(f=b);void 0!=d&&(h=d);var g=d,k=b;"normal"==e&&(b>a||d>c)&&(e="fit");if("full"==e||"fit"==e)b=h/c,g=h/b,k=f/b;"full"==e&&k<a&&(b=f/a,g=h/b,k=f/b);"fit"==e&&k>a&&(b=f/a,g=h/b,k=f/b);$(this).css({height:g+"px",width:k+"px",top:Math.round(c/2-g/2)+"px",left:Math.round(a/2-k/2)+"px"});return this};$.fn.processFont=function(a,c,b){$(this).css({"font-family":a,color:c,"font-size":b+"px"})};
$.fn.processIcon=function(a){$(this).css({"background-image":"url("+a+")","background-repeat":"no-repeat","background-position":"15px 11px"})};
