(function(p,l,q){"function"==typeof define&&define.amd?define(["jquery"],function(t){return q(t,p,l),t.mobile}):q(p.jQuery,p,l)})(this,document,function(p,l,q,t){(function(a,k,n){function g(a){return a=a||location.href,"#"+a.replace(/^[^#]*#?(.*)$/,"$1")}var e="hashchange",h=q,b,d=a.event.special,c=h.documentMode,f="on"+e in k&&(c===n||7<c);a.fn[e]=function(a){return a?this.bind(e,a):this.trigger(e)};a.fn[e].delay=50;d[e]=a.extend(d[e],{setup:function(){if(f)return!1;a(b.start)},teardown:function(){if(f)return!1;
a(b.stop)}});b=function(){function b(){var m=g(),f=r(d);m!==d?(l(d=m,f),a(k).trigger(e)):f!==d&&(location.href=location.href.replace(/#.*/,"")+f);c=setTimeout(b,a.fn[e].delay)}var m={},c,d=g(),H=function(a){return a},l=H,r=H;return m.start=function(){c||b()},m.stop=function(){c&&clearTimeout(c);c=n},k.attachEvent&&!k.addEventListener&&!f&&function(){var c,d;m.start=function(){c||(d=a.fn[e].src,d=d&&d+g(),c=a('<iframe tabindex="-1" title="empty"/>').hide().one("load",function(){d||l(g());b()}).attr("src",
d||"javascript:0").insertAfter("body")[0].contentWindow,h.onpropertychange=function(){try{"title"===event.propertyName&&(c.document.title=h.title)}catch(a){}})};m.stop=H;r=function(){return g(c.location.href)};l=function(b,m){var d=c.document,f=a.fn[e].domain;b!==m&&(d.title=h.title,d.open(),f&&d.write('<script>document.domain="'+f+'"\x3c/script>'),d.close(),c.location.hash=b)}}(),m}()})(p,this);p.mobile={};(function(a,k,n){var g={};a.mobile=a.extend(a.mobile,{version:"1.3.1",ns:"",subPageUrlKey:"ui-page",
activePageClass:"ui-page-active",activeBtnClass:"ui-btn-active",focusClass:"ui-focus",ajaxEnabled:!0,hashListeningEnabled:!0,linkBindingEnabled:!0,defaultPageTransition:"fade",maxTransitionWidth:!1,minScrollBack:250,touchOverflowEnabled:!1,defaultDialogTransition:"pop",pageLoadErrorMessage:"Error Loading Page",pageLoadErrorMessageTheme:"e",phonegapNavigationEnabled:!1,autoInitializePage:!0,pushStateEnabled:!0,ignoreContentEnabled:!1,orientationChangeEnabled:!0,buttonMarkup:{hoverDelay:200},window:a(k),
document:a(q),keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91},behaviors:{},silentScroll:function(b){"number"!==a.type(b)&&(b=a.mobile.defaultHomeScroll);a.event.special.scrollstart.enabled=
!1;setTimeout(function(){k.scrollTo(0,b);a.mobile.document.trigger("silentscroll",{x:0,y:b})},20);setTimeout(function(){a.event.special.scrollstart.enabled=!0},150)},nsNormalizeDict:g,nsNormalize:function(b){if(b)return g[b]||(g[b]=a.camelCase(a.mobile.ns+b))},getInheritedTheme:function(a,d){for(var c=a[0],f="",e=/ui-(bar|body|overlay)-([a-z])\b/,m,u;c&&!((m=c.className||"")&&(u=e.exec(m))&&(f=u[2]));)c=c.parentNode;return f||d||"a"},closestPageData:function(a){return a.closest(':jqmData(role="page"), :jqmData(role="dialog")').data("mobile-page")},
enhanceable:function(a){return this.haveParents(a,"enhance")},hijackable:function(a){return this.haveParents(a,"ajax")},haveParents:function(b,d){if(!a.mobile.ignoreContentEnabled)return b;for(var c=b.length,f=a(),e,m,u,A=0;A<c;A++){m=b.eq(A);u=!1;for(e=b[A];e;){if("false"===(e.getAttribute?e.getAttribute("data-"+a.mobile.ns+d):"")){u=!0;break}e=e.parentNode}u||(f=f.add(m))}return f},getScreenHeight:function(){return k.innerHeight||a.mobile.window.height()}},a.mobile);a.fn.jqmData=function(b,d){var c;
return"undefined"!=typeof b&&(b&&(b=a.mobile.nsNormalize(b)),2>arguments.length||d===n?c=this.data(b):c=this.data(b,d)),c};a.jqmData=function(b,d,c){var f;return"undefined"!=typeof d&&(f=a.data(b,d?a.mobile.nsNormalize(d):d,c)),f};a.fn.jqmRemoveData=function(b){return this.removeData(a.mobile.nsNormalize(b))};a.jqmRemoveData=function(b,d){return a.removeData(b,a.mobile.nsNormalize(d))};a.fn.removeWithDependents=function(){a.removeWithDependents(this)};a.removeWithDependents=function(b){b=a(b);(b.jqmData("dependents")||
a()).remove();b.remove()};a.fn.addDependents=function(b){a.addDependents(a(this),b)};a.addDependents=function(b,d){var c=a(b).jqmData("dependents")||a();a(b).jqmData("dependents",a.merge(c,d))};a.fn.getEncodedText=function(){return a("<div/>").text(a(this).text()).html()};a.fn.jqmEnhanceable=function(){return a.mobile.enhanceable(this)};a.fn.jqmHijackable=function(){return a.mobile.hijackable(this)};var e=a.find,h=/:jqmData\(([^)]*)\)/g;a.find=function(b,d,c,f){return b=b.replace(h,"[data-"+(a.mobile.ns||
"")+"$1]"),e.call(this,b,d,c,f)};a.extend(a.find,e);a.find.matches=function(b,d){return a.find(b,null,null,d)};a.find.matchesSelector=function(b,d){return 0<a.find(d,null,null,[b]).length}})(p,this);(function(a,k){l.matchMedia=l.matchMedia||function(a,g){var e,h=a.documentElement,b=h.firstElementChild||h.firstChild,d=a.createElement("body"),c=a.createElement("div");return c.id="mq-test-1",c.style.cssText="position:absolute;top:-100em",d.style.background="none",d.appendChild(c),function(a){return c.innerHTML=
'&shy;<style media="'+a+'"> #mq-test-1 { width: 42px; }</style>',h.insertBefore(d,b),e=42===c.offsetWidth,h.removeChild(d),{matches:e,media:a}}}(q);a.mobile.media=function(a){return l.matchMedia(a).matches}})(p);(function(a,k){var n={touch:"ontouchend"in q};a.mobile.support=a.mobile.support||{};a.extend(a.support,n);a.extend(a.mobile.support,n)})(p);p.extend(p.support,{orientation:"orientation"in l&&"onorientationchange"in l});(function(a,k){function n(a){var c=a.charAt(0).toUpperCase()+a.substr(1);
a=(a+" "+b.join(c+" ")+c).split(" ");for(var d in a)if(h[a[d]]!==k)return!0}function g(a,c,d){var f=q.createElement("div");d=d?d:b;for(var e,h=0;h<d.length;h++){var g=d[h],F=(""===g?"":"-"+g.charAt(0).toLowerCase()+g.substr(1)+"-")+a+": "+c+";",g=g.charAt(0).toUpperCase()+g.substr(1),g=g+(""===g?a:a.charAt(0).toUpperCase()+a.substr(1));f.setAttribute("style",F);!f.style[g]||(e=!0)}return!!e}var e=a("<body>").prependTo("html"),h=e[0].style,b=["Webkit","Moz","O"],d="palmGetResource"in l,c=l.opera,f=
l.operamini&&"[object OperaMini]"==={}.toString.call(l.operamini),F=l.blackberry&&!n("-webkit-transform");a.extend(a.mobile,{browser:{}});a.mobile.browser.oldIE=function(){var a=3,c=q.createElement("div"),d=c.all||[];do c.innerHTML="\x3c!--[if gt IE "+ ++a+"]><br><![endif]--\x3e";while(d[0]);return 4<a?a:!a}();a.extend(a.support,{cssTransitions:"WebKitTransitionEvent"in l||g("transition","height 100ms linear",["Webkit","Moz",""])&&!a.mobile.browser.oldIE&&!c,pushState:"pushState"in history&&"replaceState"in
history&&!(0<=l.navigator.userAgent.indexOf("Firefox")&&l.top!==l)&&-1===l.navigator.userAgent.search(/CriOS/),mediaquery:a.mobile.media("only all"),cssPseudoElement:!!n("content"),touchOverflow:!!n("overflowScrolling"),cssTransform3d:function(){var c=a.mobile.media("(-"+b.join("-transform-3d),(-")+"-transform-3d),(transform-3d)");if(c)return!!c;var d=q.createElement("div"),f={MozTransform:"-moz-transform",transform:"transform"};e.append(d);for(var g in f)d.style[g]!==k&&(d.style[g]="translate3d( 100px, 1px, 1px )",
c=l.getComputedStyle(d).getPropertyValue(f[g]));return!!c&&"none"!==c}(),boxShadow:!!n("boxShadow")&&!F,fixedPosition:function(){var a=navigator.userAgent,c=navigator.platform,d=a.match(/AppleWebKit\/([0-9]+)/),d=!!d&&d[1],b=a.match(/Fennec\/([0-9]+)/),b=!!b&&b[1],f=a.match(/Opera Mobi\/([0-9]+)/),e=!!f&&f[1];return(-1<c.indexOf("iPhone")||-1<c.indexOf("iPad")||-1<c.indexOf("iPod"))&&d&&534>d||l.operamini&&"[object OperaMini]"==={}.toString.call(l.operamini)||f&&7458>e||-1<a.indexOf("Android")&&d&&
533>d||b&&6>b||"palmGetResource"in l&&d&&534>d||-1<a.indexOf("MeeGo")&&-1<a.indexOf("NokiaBrowser/8.5.0")?!1:!0}(),scrollTop:("pageXOffset"in l||"scrollTop"in q.documentElement||"scrollTop"in e[0])&&!d&&!f,dynamicBaseTag:function(){var c=location.protocol+"//"+location.host+location.pathname+"ui-dir/",d=a("head base"),b=null,f="",g,h;return d.length?f=d.attr("href"):d=b=a("<base>",{href:c}).appendTo("head"),g=a("<a href='testurl' />").prependTo(e),h=g[0].href,d[0].href=f||location.pathname,b&&b.remove(),
0===h.indexOf(c)}(),cssPointerEvents:function(){var a=q.createElement("x"),c=q.documentElement,d=l.getComputedStyle,b;return"pointerEvents"in a.style?(a.style.pointerEvents="auto",a.style.pointerEvents="x",c.appendChild(a),b=d&&"auto"===d(a,"").pointerEvents,c.removeChild(a),!!b):!1}(),boundingRect:"undefined"!=typeof q.createElement("div").getBoundingClientRect});e.remove();d=function(){var a=l.navigator.userAgent;return-1<a.indexOf("Nokia")&&(-1<a.indexOf("Symbian/3")||-1<a.indexOf("Series60/5"))&&
-1<a.indexOf("AppleWebKit")&&a.match(/(BrowserNG|NokiaBrowser)\/7\.[0-3]/)}();a.mobile.gradeA=function(){return(a.support.mediaquery||a.mobile.browser.oldIE&&7<=a.mobile.browser.oldIE)&&(a.support.boundingRect||null!==a.fn.jquery.match(/1\.[0-7+]\.[0-9+]?/))};a.mobile.ajaxBlacklist=l.blackberry&&!l.WebKitPoint||f||d;d&&a(function(){a("head link[rel='stylesheet']").attr("rel","alternate stylesheet").attr("rel","stylesheet")});a.support.boxShadow||a("html").addClass("ui-mobile-nosupport-boxshadow")})(p);
(function(a,k){var n=a.mobile.window,g;a.event.special.navigate=g={bound:!1,pushStateEnabled:!0,originalEventName:k,isPushStateEnabled:function(){return a.support.pushState&&!0===a.mobile.pushStateEnabled&&this.isHashChangeEnabled()},isHashChangeEnabled:function(){return!0===a.mobile.hashListeningEnabled},popstate:function(e){var g=new a.Event("navigate"),b=new a.Event("beforenavigate"),d=e.originalEvent.state||{};n.trigger(b);b.isDefaultPrevented()||(e.historyState&&a.extend(d,e.historyState),g.originalEvent=
e,setTimeout(function(){n.trigger(g,{state:d})},0))},hashchange:function(e,g){var b=new a.Event("navigate"),d=new a.Event("beforenavigate");n.trigger(d);d.isDefaultPrevented()||(b.originalEvent=e,n.trigger(b,{state:e.hashchangeState||{}}))},setup:function(a,h){g.bound||(g.bound=!0,g.isPushStateEnabled()?(g.originalEventName="popstate",n.bind("popstate.navigate",g.popstate)):g.isHashChangeEnabled()&&(g.originalEventName="hashchange",n.bind("hashchange.navigate",g.hashchange)))}}})(p);(function(a){a.event.special.throttledresize=
{setup:function(){a(this).bind("resize",k)},teardown:function(){a(this).unbind("resize",k)}};var k=function(){e=(new Date).getTime();h=e-n;250<=h?(n=e,a(this).trigger("throttledresize")):(g&&clearTimeout(g),g=setTimeout(k,250-h))},n=0,g,e,h})(p);(function(a,k){function n(){var a=h();a!==b&&(b=a,g.trigger(e))}var g=a(k),e="orientationchange",h,b,d,c,f={0:!0,180:!0};a.support.orientation&&(d=k.innerWidth||g.width(),c=k.innerHeight||g.height(),d=d>c&&50<d-c,c=f[k.orientation],d&&c||!d&&!c)&&(f={"-90":!0,
90:!0});a.event.special.orientationchange=a.extend({},a.event.special.orientationchange,{setup:function(){if(a.support.orientation&&!a.event.special.orientationchange.disabled)return!1;b=h();g.bind("throttledresize",n)},teardown:function(){if(a.support.orientation&&!a.event.special.orientationchange.disabled)return!1;g.unbind("throttledresize",n)},add:function(a){var c=a.handler;a.handler=function(a){return a.orientation=h(),c.apply(this,arguments)}}});a.event.special.orientationchange.orientation=
h=function(){var c=!0,d=q.documentElement;return a.support.orientation?c=f[k.orientation]:c=d&&1.1>d.clientWidth/d.clientHeight,c?"portrait":"landscape"};a.fn[e]=function(a){return a?this.bind(e,a):this.trigger(e)};a.attrFn&&(a.attrFn[e]=!0)})(p,this);(function(a,k,n,g){function e(a){for(;a&&"undefined"!=typeof a.originalEvent;)a=a.originalEvent;return a}function h(c){for(var d={},b,f;c;){b=a.data(c,r);for(f in b)b[f]&&(d[f]=d.hasVirtualBinding=!0);c=c.parentNode}return d}function b(){v&&(clearTimeout(v),
v=0);v=setTimeout(function(){x=v=0;C.length=0;I=!1;y=!0},a.vmouse.resetTimerDuration)}function d(c,d,b){var f,h;if(!(h=b&&b[c])){if(b=!b)a:{for(b=d.target;b;){if((h=a.data(b,r))&&(!c||h[c]))break a;b=b.parentNode}b=null}h=b}if(h){f=d;b=f.type;var m,k;f=a.Event(f);f.type=c;c=f.originalEvent;h=a.event.props;-1<b.search(/^(mouse|click)/)&&(h=B);if(c)for(k=h.length,m;k;)m=h[--k],f[m]=c[m];-1<b.search(/mouse(down|up)|click/)&&!f.which&&(f.which=1);if(-1!==b.search(/^touch/)&&(m=e(c),b=m.touches,m=m.changedTouches,
c=b&&b.length?b[0]:m&&m.length?m[0]:g))for(b=0,h=z.length;b<h;b++)m=z[b],f[m]=c[m];a(d.target).trigger(f)}return f}function c(c){var b=a.data(c.target,G);I||x&&x===b||(b=d("v"+c.type,c))&&(b.isDefaultPrevented()&&c.preventDefault(),b.isPropagationStopped()&&c.stopPropagation(),b.isImmediatePropagationStopped()&&c.stopImmediatePropagation())}function f(c){var b=e(c).touches,f;b&&1===b.length&&(f=c.target,b=h(f),b.hasVirtualBinding&&(x=N++,a.data(f,G,x),v&&(clearTimeout(v),v=0),w=y=!1,f=e(c).touches[0],
t=f.pageX,L=f.pageY,d("vmouseover",c,b),d("vmousedown",c,b)))}function l(a){y||(w||d("vmousecancel",a,h(a.target)),w=!0,b())}function m(c){if(!y){var f=e(c).touches[0],g=w,m=a.vmouse.moveDistanceThreshold,k=h(c.target);(w=w||Math.abs(f.pageX-t)>m||Math.abs(f.pageY-L)>m)&&!g&&d("vmousecancel",c,k);d("vmousemove",c,k);b()}}function u(a){if(!y){y=!0;var c=h(a.target),f;d("vmouseup",a,c);if(!w){var g=d("vclick",a,c);g&&g.isDefaultPrevented()&&(f=e(a).changedTouches[0],C.push({touchID:x,x:f.clientX,y:f.clientY}),
I=!0)}d("vmouseout",a,c);w=!1;b()}}function p(c){c=a.data(c,r);var b;if(c)for(b in c)if(c[b])return!0;return!1}function q(){}function M(b){var d=b.substr(1);return{setup:function(g,e){p(this)||a.data(this,r,{});a.data(this,r)[b]=!0;s[b]=(s[b]||0)+1;1===s[b]&&D.bind(d,c);a(this).bind(d,q);J&&(s.touchstart=(s.touchstart||0)+1,1===s.touchstart&&D.bind("touchstart",f).bind("touchend",u).bind("touchmove",m).bind("scroll",l))},teardown:function(g,e){--s[b];s[b]||D.unbind(d,c);J&&(--s.touchstart,s.touchstart||
D.unbind("touchstart",f).unbind("touchmove",m).unbind("touchend",u).unbind("scroll",l));var h=a(this),k=a.data(this,r);k&&(k[b]=!1);h.unbind(d,q);p(this)||h.removeData(r)}}}var r="virtualMouseBindings",G="virtualTouchID";k="vmouseover vmousedown vmousemove vmouseup vclick vmouseout vmousecancel".split(" ");var z="clientX clientY pageX pageY screenX screenY".split(" "),B=a.event.props.concat(a.event.mouseHooks?a.event.mouseHooks.props:[]),s={},v=0,t=0,L=0,w=!1,C=[],I=!1,y=!1,J="addEventListener"in
n,D=a(n),N=1,x=0,K;a.vmouse={moveDistanceThreshold:10,clickDistanceThreshold:10,resetTimerDuration:1500};for(var E=0;E<k.length;E++)a.event.special[k[E]]=M(k[E]);J&&n.addEventListener("click",function(c){var b=C.length,d=c.target,f,g,e,h,m;if(b)for(f=c.clientX,g=c.clientY,K=a.vmouse.clickDistanceThreshold,e=d;e;){for(h=0;h<b;h++)if(m=C[h],e===d&&Math.abs(m.x-f)<K&&Math.abs(m.y-g)<K||a.data(e,G)===m.touchID){c.preventDefault();c.stopPropagation();return}e=e.parentNode}},!0)})(p,l,q);(function(a,k,
l){function g(c,b,d){var e=d.type;d.type=b;a.event.dispatch.call(c,d);d.type=e}var e=a(q);a.each("touchstart touchmove touchend tap taphold swipe swipeleft swiperight scrollstart scrollstop".split(" "),function(c,b){a.fn[b]=function(a){return a?this.bind(b,a):this.trigger(b)};a.attrFn&&(a.attrFn[b]=!0)});var h=(k=a.mobile.support.touch)?"touchstart":"mousedown",b=k?"touchend":"mouseup",d=k?"touchmove":"mousemove";a.event.special.scrollstart={enabled:!0,setup:function(){function c(a,c){d=c;g(b,d?"scrollstart":
"scrollstop",a)}var b=this,d,e;a(b).bind("touchmove scroll",function(b){a.event.special.scrollstart.enabled&&(d||c(b,!0),clearTimeout(e),e=setTimeout(function(){c(b,!1)},50))})}};a.event.special.tap={tapholdThreshold:750,setup:function(){var c=this,b=a(c);b.bind("vmousedown",function(d){function h(){clearTimeout(p)}function k(){h();b.unbind("vclick",l).unbind("vmouseup",h);e.unbind("vmousecancel",k)}function l(a){k();n===a.target&&g(c,"tap",a)}if(d.which&&1!==d.which)return!1;var n=d.target,p;b.bind("vmouseup",
h).bind("vclick",l);e.bind("vmousecancel",k);p=setTimeout(function(){g(c,"taphold",a.Event("taphold",{target:n}))},a.event.special.tap.tapholdThreshold)})}};a.event.special.swipe={scrollSupressionThreshold:30,durationThreshold:1E3,horizontalDistanceThreshold:30,verticalDistanceThreshold:75,start:function(c){var b=c.originalEvent.touches?c.originalEvent.touches[0]:c;return{time:(new Date).getTime(),coords:[b.pageX,b.pageY],origin:a(c.target)}},stop:function(a){a=a.originalEvent.touches?a.originalEvent.touches[0]:
a;return{time:(new Date).getTime(),coords:[a.pageX,a.pageY]}},handleSwipe:function(b,d){d.time-b.time<a.event.special.swipe.durationThreshold&&Math.abs(b.coords[0]-d.coords[0])>a.event.special.swipe.horizontalDistanceThreshold&&Math.abs(b.coords[1]-d.coords[1])<a.event.special.swipe.verticalDistanceThreshold&&b.origin.trigger("swipe").trigger(b.coords[0]>d.coords[0]?"swipeleft":"swiperight")},setup:function(){var c=a(this);c.bind(h,function(f){function e(b){g&&(h=a.event.special.swipe.stop(b),Math.abs(g.coords[0]-
h.coords[0])>a.event.special.swipe.scrollSupressionThreshold&&b.preventDefault())}var g=a.event.special.swipe.start(f),h;c.bind(d,e).one(b,function(){c.unbind(d,e);g&&h&&a.event.special.swipe.handleSwipe(g,h);g=h=l})})}};a.each({scrollstop:"scrollstart",taphold:"tap",swipeleft:"swipe",swiperight:"swipe"},function(b,d){a.event.special[b]={setup:function(){a(this).bind(d,a.noop)}}})})(p,this);(function(a,k,l){var g=function(e){return e===l&&(e=!0),function(b,d,c,f){var g=new a.Deferred,m=d?" reverse":
"",l=a.mobile.urlHistory.getActive().lastScroll||a.mobile.defaultHomeScroll,n=a.mobile.getScreenHeight(),p=!1!==a.mobile.maxTransitionWidth&&a.mobile.window.width()>a.mobile.maxTransitionWidth,q=!a.support.cssTransitions||p||!b||"none"===b||Math.max(a.mobile.window.scrollTop(),l)>a.mobile.getMaxScrollForTransition(),r=function(){a.mobile.pageContainer.toggleClass("ui-mobile-viewport-transitioning viewport-"+b)},t=function(){a.event.special.scrollstart.enabled=!1;k.scrollTo(0,l);setTimeout(function(){a.event.special.scrollstart.enabled=
!0},150)},z=function(){f.removeClass(a.mobile.activePageClass+" out in reverse "+b).height("")},p=function(){f&&e&&z();c.css("z-index",-10);c.addClass(a.mobile.activePageClass+" ui-page-pre-in");a.mobile.focusPage(c);c.height(n+l);t();c.css("z-index","");q||c.animationComplete(B);c.removeClass(" ui-page-pre-in").addClass(b+" in"+m);q&&B()},B=function(){e||f&&z();c.removeClass("out in reverse "+b).height("");r();a.mobile.window.scrollTop()!==l&&t();g.resolve(b,d,c,f,!0)};r();f&&!q?(e?f.animationComplete(p):
p(),f.height(n+a.mobile.window.scrollTop()).addClass(b+" out"+m)):p();return g.promise()}},e=g(),g=g(!1);a.mobile.defaultTransitionHandler=e;a.mobile.transitionHandlers={"default":a.mobile.defaultTransitionHandler,sequential:e,simultaneous:g};a.mobile.transitionFallbacks={};a.mobile._maybeDegradeTransition=function(e){return e&&!a.support.cssTransform3d&&a.mobile.transitionFallbacks[e]&&(e=a.mobile.transitionFallbacks[e]),e};a.mobile.getMaxScrollForTransition=a.mobile.getMaxScrollForTransition||function(){return 3*
a.mobile.getScreenHeight()}})(p,this)});
