define(["jquery","ui-elements","utils/utils"],function(a){var f=function(b,d){a(document).ready(a.proxy(function(){this.post_type=b;this.image_meta=d;this.items=[];var c=a("#wpbody-content");this.$holder=a("<div id='customPortfolioHolder'></div>").appendTo(c);this.loadWorks()},this))};f.prototype={loadWorks:function(){this.$holder.html('<p>Loading grid <img src="'+template_directory+'/plusquare_admin/config-backend/images/ui/loading.gif" /></p>');jQuery.post(adminAjax,{action:"pq_custom_grid_listing",
type:this.post_type,image_meta:this.image_meta},a.proxy(function(a){this.$holder.html(a);this.worksLoaded()},this))},worksLoaded:function(){a("#queryContainer .item").each(a.proxy(function(b,d){var c=new g(a(d),this.items.length);this.items.push(c);a(c).bind("itemStartDrag",a.proxy(this.itemStartDrag,this));a(c).bind("itemMove",a.proxy(this.itemMove,this));a(c).bind("itemStopDrag",a.proxy(this.itemStopDrag,this))},this));a("#toogleTrash").click(a.proxy(this.toogleTrash,this));this.$trashHolder=a("#queryTrashContainer").css("display",
"none");a(".items-grid",this.$trashHolder).css("width",165*a("#queryTrashContainer .item").length+"px");a(".save_button").click(a.proxy(this.save,this))},toogleTrash:function(){this.$trashHolder.not(":animated").slideToggle(200);return!1},itemStartDrag:function(){this.$grid=a("#queryContainer");var b=this.$grid.offset();this.gridLeft=b.left;this.gridTop=b.top;this.itemsPerRow=Math.floor(this.$grid.width()/165);this.itemsHeight=this.items[0].$item.outerHeight();this.numLines=Math.ceil(this.items.length/
this.itemsPerRow)},itemMove:function(a,d,c,e){a=d-this.gridLeft;c-=this.gridTop;a=77>a?0:Math.round(a/165);a>this.itemsPerRow&&(a=this.itemsPerRow);c=Math.floor(c/this.itemsHeight);0>c?c=0:c>=this.numLines&&(c=this.numLines-1);c=c*this.itemsPerRow+a;c>this.items.length&&(c=this.items.length);e!=c&&e+1!=c&&this.changeItemPosition(e,c<e?c:c-1)},changeItemPosition:function(b,d){var c=this.items[b];c.$item.remove();0==d?this.$grid.prepend(c.$item):a(">div:nth-child("+d+")",this.$grid).after(c.$item);
c.rebind();this.items=removePositionInArray(this.items,b);this.items.splice(d,0,c);this.updateItemsIds()},updateItemsIds:function(){a.each(this.items,function(a,d){d.gridId=a})},itemStopDrag:function(){a.each(this.items,function(a,d){})},save:function(){a(".loading_status").css("display","inline-block");a(".save_button").css("display","none");var b="{";a.each(this.items,function(a,c){0!=a&&(b+=",");b+='"'+c.postId+'":"'+a+'"'});b+="}";a.post(adminAjax,{action:"ajax_update_posts_meta",key:"position",
values:b},function(b){a(".loading_status").css("display","none");a(".save_button").css("display","")});return!1}};var g=function(b,d){this.$item=b;this.postId=b.attr("rel");this.gridId=d;this.$dragArea=a(".dragArea",b);this.$dragArea.bind(mouseDownBind,a.proxy(this.startDragging,this))};g.prototype={getSizing:function(){return this.comboBox.val()},rebind:function(){this.$dragArea.unbind(mouseDownBind);this.$dragArea.bind(mouseDownBind,a.proxy(this.startDragging,this))},updateMeta:function(){a.post(adminAjax,
{action:"ajax_update_meta",post_id:this.postId,key:"position",value:this.gridId},function(a){})},startDragging:function(b){this.$dragArea.addClass("active");this.$draggingObj=this.$item.clone().appendTo(a("body"));this.$item.stop().fadeTo(200,0.5);var d=this.$item.offset();this.x=b.pageX;this.y=b.pageY;this.posX=d.left;this.posY=d.top;this.$draggingObj.css({position:"absolute"});this.updateDraggingObj();a(document).bind(mouseMoveBind,a.proxy(this.move,this));a(document).bind(mouseUpBind,a.proxy(this.stopDragging,
this));a(this).trigger("itemStartDrag");return!1},updateDraggingObj:function(){this.$draggingObj.css({top:this.posY,left:this.posX})},move:function(b){var d=b.pageX;b=b.pageY;this.posX+=d-this.x;this.posY+=b-this.y;this.x=d;this.y=b;this.updateDraggingObj();a(this).trigger("itemMove",[this.posX+70,this.posY+80,this.gridId]);return!1},stopDragging:function(){a(document).unbind(mouseMoveBind);a(document).unbind(mouseUpBind);this.$dragArea.removeClass("active");this.$item.stop().fadeTo(200,1);var b=
this.$item.offset();this.$draggingObj.stop().animate({opacity:0,top:b.top,left:b.left},300,function(){a(this).remove()});a(this).trigger("itemStopDrag");return!1}};return f});
