define("jquery libraries/jquery.mobile.vmouse ./PageBuilder/ModuleButton ./PageBuilder/Module ./PageBuilder/Tooltip utils/utils ui-elements".split(" "),function(a,q,s,r){var n;q=function(b,d,c,g,e,f,h){n=f;builderPath=e;$body=a("body");null==h&&(h=void 0);this.modules=[];this.lineNum=0;this.parsingFromHtml=!1;this.$input=b;this.multiple=g;this.rowShortcode=h;this.$placeholdersHolder=d;this.$menuHolder=c;this.build();this.moduleDragging=-1;a(window).resize(a.proxy(this.onResize,this));this.fromHtml();
this.menuFromTop=this.$pageBuilderMenu.offset().top;this.menuOffTop=a("#wpbody").offset().top;a(window).scroll(a.proxy(this.onScroll,this))};q.prototype={build:function(){this.$pageBuilderMenu=a("<div class='menu'></div>").appendTo(this.$menuHolder);if(this.multiple){var b=a("<div class='menu-button'></div>").appendTo(this.$pageBuilderMenu),b=a("<a href='#'>Add new placeholder</a>").appendTo(b);b.processIcon(builderPath+"images/page_builder/MainMenu/placeholder_icon.png");b.click(a.proxy(this.createPlaceholder,
this))}b=a("<div class='menu-button'></div>").appendTo(this.$pageBuilderMenu);a("<a href='#'>Add new module</a>").appendTo(b).processIcon(builderPath+"images/page_builder/MainMenu/add_icon.png");var d=a("<div class='menu-dropdown' id='modulesDrop' style='"+(this.multiple?"":"left: -1px;")+"'></div>").appendTo(b);b.hover(function(){d.stop().css("display","block").fadeTo(200,1)},function(){d.stop().fadeTo(200,0,function(){a(this).css("display","none")})});a("<p class='title_menu' style='margin-top:0;'>Shortcodes</p>").appendTo(d);
var c=a("<div class='row-fluid columns-wraper'></div>").appendTo(d),b=a("<div class='span3 column'></div>").appendTo(c),g=a("<div class='span3 column'></div>").appendTo(c),e=a("<div class='span3 column'></div>").appendTo(c),c=a("<div class='span3 column'></div>").appendTo(c),f=[b,g,e,c],b=0,h;for(h in n)n.hasOwnProperty(h)&&b++;var k=Math.ceil(b/4),m=0,l=0;a.each(n,a.proxy(function(b,c){var d=new s.ComponentButton(c);f[l].append(d.$obj);m++;m==k&&(m=0,l++);a(d).bind("moduleButtonDown",a.proxy(this.createComponent,
this))},this));this.$viewHolder=a("<div class='viewHolder'></div>").appendTo(this.$placeholdersHolder.parent())},clearAll:function(){a.each(this.modules,function(b,a){a.$obj.remove()});this.modules=[]},parseComponents:function(b,d){var c=RegExp("\\[.*?\\]","gi");do{var g=b.match(c);if(null!=g){for(var e=g[0],f="",h=1;" "!=e.charAt(h)&&"]"!=e.charAt(h);)f+=e.charAt(h),h++;var k=b.match(RegExp("\\["+f+".*?\\][\\s\\S]*?\\[\\/"+f+"\\]","gi"));if(null!=k){k=k[0];WP_DEBUG&&console.log("Creating component with shortcode: "+
f);WP_DEBUG&&console.log("Component: "+k);b=b.substring(k.length);WP_DEBUG&&console.log("Rest: "+b);var m=e,e=n[f],l=new r.Component(e),p=function(b){if("content"!=b.associate){WP_DEBUG&&console.log(b.associate);var a=RegExp(b.associate+'=".*?"',"i");WP_DEBUG&&console.log(m);a=m.match(a);if(null!=a&&(a=a[0],null!=a)){var c=a.substring(b.associate.length+2,a.length-1);WP_DEBUG&&console.log(b.associate+": "+c);l.parameters[b.id].value=c}}else c=m.length,a=k.length-(f.length+3),c=a-1<=c?"":k.substring(c,
a),WP_DEBUG&&console.log("shortcode content:"+c),l.parameters[b.id].value=c;return c};a.each(e.options,function(b,c){if("tabs"==c.type||"tabs_unbinded"==c.type)if("tabs"==c.type){var d=p(c);a.each(c.tabs[d],function(b,a){p(a)})}else a.each(c.tabs,function(b,c){a.each(c,function(b,a){p(a)})});else p(c)});d.addComponent(l);l.build();a(l).bind("moduleDown",a.proxy(this.componentDown,this));a(l).bind("changed",a.proxy(this.makeHtml,this))}}}while(null!=g&&1<b.length)},fromHtml:function(){var b=this.$input.val();
this.clearAll();WP_DEBUG&&console.log("\n\nCONTENT:"+b);var a=!1;void 0!=this.rowShortcode&&(a=!0);if(null!=b&&void 0!=b&&""!=b){this.parsingFromHtml=!0;if(a){if(c="\\["+this.rowShortcode+".*?\\][\\s\\S]*?\\[\\/"+this.rowShortcode+"\\]",c=RegExp(c,"gi"),c=b.match(c),null!=c)for(g=0;g<c.length;g++){WP_DEBUG&&console.log(this.rowShortcode+":"+c[g]);e="\\["+this.rowShortcode+".*?\\]";e=RegExp(e,"gi");f=c[g].match(e);if(null==f){WP_DEBUG&&console.log("Page Builder error");return}this.createPlaceholder(null);
e=this.modules[this.modules.length-1];f=c[g].substring(f[0].length,c[g].length-9-(this.rowShortcode.length-6));WP_DEBUG&&console.log(this.rowShortcode+" content: "+f);this.parseComponents(f,e)}}else if(b=b.match(RegExp("\\[row\\][\\s\\S]*?\\[\\/row\\]","gi")),null!=b)for(a=0;a<b.length;a++){WP_DEBUG&&console.log("ROW:"+b[a]);var c="\\[column.*?\\][\\s\\S]*?\\[\\/column\\]",c=RegExp(c,"gi"),c=b[a].match(c);if(null!=c)for(var g=0;g<c.length;g++){WP_DEBUG&&console.log("COLUMN:"+c[g]);var e="\\[column.*?\\]",
e=RegExp(e,"gi"),f=c[g].match(e);if(null==f){WP_DEBUG&&console.log("Page Builder error");return}this.createPlaceholder(null);e=this.modules[this.modules.length-1];f=c[g].substring(f[0].length,c[g].length-9);WP_DEBUG&&console.log("column content: "+f);this.parseComponents(f,e)}}this.parsingFromHtml=!1}0==this.modules.length&&this.createPlaceholder()},makeHtml:function(){if(!this.parsingFromHtml){for(var b="",a=0;a<this.modules.length;a++)var c=this.modules[a],b=void 0!=this.rowShortcode?b+("["+this.rowShortcode+
"]"):b+"[row]",b=b+c.getHtml(0,void 0==this.rowShortcode),b=void 0!=this.rowShortcode?b+("[/"+this.rowShortcode+"]"):b+"[/row]";this.$input.val(b).trigger("change");WP_DEBUG&&console.log(b);return!0}},createComponent:function(b,d){this.module=new r.Component(n[d],this.$viewHolder);this.type="module";this.targetPlaceholder=-1;for(var c=1;c<this.modules.length;c++)this.modules[c].offsetTop=this.modules[c].$obj.offset().top;a(b.target).bind("moduleButtonMove",a.proxy(this.movingComponentInit,this));
a(b.target).bind("moduleButtonUp",a.proxy(this.createModuleFinal,this))},processComponentMoving:function(b,a){if(-1!=b){if(this.targetPlaceholder!=b){var c=this.modules[b];-1!=this.targetPlaceholder&&this.modules[this.targetPlaceholder].cancelAbove();c.componentAbove(a);this.targetPlaceholder=b}}else-1!=this.targetPlaceholder&&this.modules[this.targetPlaceholder].cancelAbove(),this.targetPlaceholder=-1},movingComponentInit:function(b,a,c){a=this.getGridPos(c);this.processComponentMoving(a,b.target.info.color)},
createPlaceholder:function(b){b=new r.Placeholder(12,0,this.modules.length,!1);this.modules.push(b);this.$placeholdersHolder.append(b.$obj);b.show();b.$obj.css("margin-bottom","5px");a(b).bind("change",a.proxy(this.makeHtml,this));a(b).bind("moduleDelete",a.proxy(this.placeholderDelete,this));a(b).bind("moduleDuplicateInsert",a.proxy(this.duplicateInsertGrid,this));this.makeHtml();a(this).trigger("placeholderAdded",["",this.modules.length]);return!1},createModuleFinal:function(b){a(b.target).unbind("moduleButtonMove");
a(b.target).unbind("moduleButtonUp");-1!=this.targetPlaceholder&&(this.modules[this.targetPlaceholder].addComponent(this.module),this.module.build(),a(this.module).bind("moduleDown",a.proxy(this.componentDown,this)),a(this.module).bind("changed",a.proxy(this.makeHtml,this)),a(this.module).bind("moduleDelete",a.proxy(this.makeHtml,this)),this.makeHtml());return!1},duplicateInsertGrid:function(b,d){a(d).bind("moduleDown",a.proxy(this.componentDown,this));a(d).bind("changed",a.proxy(this.makeHtml,this));
a("html, body").animate({scrollTop:d.$obj.offset().top+"px"},300)},placeholderDelete:function(b,d){this.modules[d].$obj.remove();this.modules=removePositionInArray(this.modules,d);for(var c=0;c<this.modules.length;c++)this.modules[c].number=c;0==this.modules.length&&this.createPlaceholder();this.makeHtml();a(this).trigger("placeholderRemoved",d);return!1},componentDown:function(b){WP_DEBUG&&console.log("componentDown");this.targetPlaceholder=b.target.placeholder;a(b.target).bind("moduleMove",a.proxy(this.movingComponent,
this));a(b.target).bind("moduleUp",a.proxy(this.placeComponent,this));return!1},movingComponent:function(b,a,c){b=b.target;a=this.getGridPos(c);a!=b.placeholder?this.processComponentMoving(a,b.info.color):(this.modules[b.placeholder].movingComponent(c,b.number),this.targetPlaceholder!=b.placeholder&&this.modules[this.targetPlaceholder].cancelAbove(),this.targetPlaceholder=b.placeholder);return!1},placeComponent:function(b){a(b.target).unbind("moduleMove");a(b.target).unbind("moduleUp");var d=b.target.placeholder;
-1!=this.targetPlaceholder&&this.targetPlaceholder!=d&&(this.modules[d].removeComponent(b.target.number),this.modules[this.targetPlaceholder].addComponent(b.target));this.makeHtml();return!1},onScroll:function(){var b=a(window).scrollTop();this.menuFromTop=this.$menuHolder.offset().top;b>this.menuFromTop-this.menuOffTop?this.$pageBuilderMenu.css({top:b-this.menuFromTop+this.menuOffTop+"px"}):this.$pageBuilderMenu.css({top:"0px"})},currentOverLine:function(b,a){this.lineOver=a;return!1},getGridPos:function(b){for(var a=
-1,c=this.modules.length-1;0<c;c--)if(b>this.modules[c].offsetTop){a=c;break}-1==a&&(a=0);return a}};return q});
