define(["jquery","jquery/jquery.easing.1.3","utils/utils"],function(a){function M(){var e=a(this).attr("href"),f=a(this).attr("data-group"),c=a(this).attr("data-type"),b=parseInt(a(this).attr("data-num"),10),d;d=void 0!=a(this).data("description")?a("body").find("#"+a(this).data("description")):a(this).find(".description");c=void 0==c?"image":c;"image"==c&&(h=parseInt(a(this).data("width"),10),k=parseInt(a(this).data("height"),10));B(e,c,f,b,0<d.length?d:!1);return!1}function B(e,f,c,b,g){var C=a("body");
x=!1;l=c;d=b;u.appendTo(C).stop().fadeTo(0,0).fadeTo(250,0.85,"easeOutExpo");m.appendTo(C).stop().fadeTo(0,0).fadeTo(250,1,"easeOutExpo");q.stop().fadeTo(0,0);D(e,f,g);E();y.unbind(clickBind).bind(clickBind,F);z.unbind(clickBind).bind(clickBind,F);r.unbind(clickBind).bind(clickBind,G);s.unbind(clickBind).bind(clickBind,H);v.unbind(clickBind).bind(clickBind,N);a(document).keypress(I)}function D(e,f,c){p=!1!=c?c.clone().addClass("description").show():!1;type=f;u.addClass("loading");if("image"==type)f=
a(window).width(),c=a(window).height(),700>=f||500>=c||(f*=0.8,c*=0.9),jQuery.post(adminAjax,{action:"pq_get_resized",url:e,retina:1<window.devicePixelRatio?"true":"false",width:f,height:c,crop:"false",snap:"true",adjust:"true",frontend:"true"},a.proxy(function(b){!0==b.success&&(WP_DEBUG&&console.log(b),n=a("<img />").attr("src",b.data.url).load(A),h=parseInt(b.data.width,10),k=parseInt(b.data.height,10))}));else if("video"==type)n=a('<iframe src="'+e+'" width="500" height="500" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>'),
A();else if("sound"==type||"soundcloud"==type)n=a("<div></div>").load(e,A)}function A(){if("image"==type){if(isNaN(h)||isNaN(k))h=n.get(0).width,k=n.get(0).height}else if("video"==type)h=1E3,k=620;else if("sound"==type||"soundcloud"==type)h=700,k=100;w();q.append(n).stop().fadeTo(300,1,"easeOutExpo");"sound"!=type&&"soundcloud"!=type||runShortcodes();p&&(!1!==p&&(t=a("<div class='description_holder'></div>").append(p)),x?t.show():t.hide(),q.append(t));u.removeClass("loading");a(window).unbind("resize",
w);a(window).resize(w);w()}function N(){(x=x?!1:!0)?(t.stop().fadeTo(1,0).show(),w(),t.fadeTo(300,1)):t.stop().fadeTo(300,0,function(){a(this).hide()})}function O(){J();var a=g[l][d].content,f=g[l][d].description,c=g[l][d].type;"image"==c&&(h=g[l][d].width,k=g[l][d].height);D(a,c,0<f.length?f:!1);E()}function K(a){d=a;q.stop().fadeTo(200,0,"easeOutExpo",O)}function H(){d<g[l].length-1&&K(d+1);return!1}function G(){0<d&&K(d-1);return!1}function I(a){37==a.keyCode?G():39==a.keyCode&&H()}function E(){!1===
p?v.css("display","none"):v.css("display","inline");if(void 0==l)r.css("display","none"),s.css("display","none");else{var a=g[l].length;r.css("display","");s.css("display","");0>=d?r.addClass("disabled"):r.removeClass("disabled");d>=a-1?s.addClass("disabled"):s.removeClass("disabled")}}function w(){var e=a(window).width(),f=a(window).height();700>=e||500>=f?(e-=20,f-=20):(e*=0.8,f*=0.9);var c=h,b=k;if(c>e||b>f)b=k/f,c=h/b,b=k/b,c>e&&(b=h/e,c=h/b,b=k/b);"sound"==type||"soundcloud"==type?(n.css({width:c+
"px",height:"auto"}),b=n.height()):n.css({width:c+"px",height:b+"px"});q.css({top:-b/2+"px",left:-c/2+"px"});!1!=p&&(e=p.height(),p.css("margin-top",b/2-e/2+"px"))}function J(){q.empty()}function F(){y.unbind(clickBind);z.unbind(clickBind);r.unbind(clickBind);s.unbind(clickBind);v.unbind(clickBind);a(document).unbind("keypress",I);u.stop().fadeTo(250,0,"easeOutExpo",function(){a(this).remove()});m.stop().fadeTo(250,0,"easeOutExpo",function(){a(this).remove()});setTimeout(J,250);return!1}var u,m,L,
q,t,y,r,s,v,z,g,p,x,l,d,n,h,k;a(document).ready(function(){window.devicePixelRatio=window.devicePixelRatio||Math.round(window.screen.availWidth/document.documentElement.clientWidth);u=a("<div class='lightbox_cover'></div>");$loadingclip=a('<div class="big-loading"><img src="'+template_directory+'/img/loaders/loader.png" alt="Be patient..." /></div>').appendTo(u);m=a("<div class='lightbox_holder'></div>");y=a("<div class='close_area'></div>").appendTo(m);L=a("<div class='lightbox_content_holder'></div>").appendTo(m);
q=a("<div class='lightbox_content'></div>").appendTo(L);r=a("<a href='#' class='lightbox_button previous' onclick='return false;'></a>").appendTo(m);s=a("<a href='#' class='lightbox_button next' onclick='return false;'></a>").appendTo(m);v=a("<a href='#' class='lightbox_button desc' onclick='return false;'></a>").appendTo(m);z=a("<a href='#' class='lightbox_button close' onclick='return false;'></a>").appendTo(m)});return{getElements:function(){var e=a(".lightbox");g={};e.each(function(f,c){var b=
a(c),e=b.attr("data-group");if(void 0!=e){g.hasOwnProperty(e)||(g[e]=[]);b.attr("data-num",g[e].length);var d={};d.content=b.attr("href");d.type=b.attr("data-type");d.type=void 0==d.type?"image":d.type;d.width=b.data("width");d.height=b.data("height");void 0!=b.data("description")?d.description=a("body").find("#"+b.data("description")):d.description=b.find(".description");g[e].push(d)}});e.bind(clickBind,M)},open:B}});
