define(["jquery","jquery/jquery.mobile.vmouse","utils/utils"],function(d){var e=function(a){this.position=0;this.time=1E3;this.$holder=a;this.$slide=a.find(".sliding_text");this.$holder.bind(mouseOverBind,d.proxy(this.startTween,this));this.$holder.bind(mouseOutBind,d.proxy(this.stopTween,this))};e.prototype={startTween:function(){this.overplus=this.$slide.width()-this.$holder.width();this.time=50*this.overplus;0<this.overplus&&this.tweenLeft()},tweenLeft:function(){this.$slide.stop().animate({left:-this.overplus+
"px"},this.time,d.proxy(this.tweenRight,this))},tweenRight:function(){this.$slide.stop().animate({left:"0px"},this.time,d.proxy(this.tweenLeft,this))},stopTween:function(){this.$slide.stop().animate({left:"0px"},500)}};var f=function(a,b){jQuery(document).ready(d.proxy(function(c){this.defaultVolume=70;this.url=b;this.$player=a;this.$tooglePlay=this.$player.find(".tooglePlay");this.$bar1=this.$player.find(".volume_bar1");this.$bar2=this.$player.find(".volume_bar2");this.$toogleMute=this.$player.find(".toogleMute");
this.$volActiveBar=this.$player.find(".volume_bar_holder .active_bar");this.$volBar=this.$player.find(".volume_bar_holder");this.$streamBar=this.$player.find(".stream_bar");this.$progressBar=this.$player.find(".progress_bars .active_bar");this.$progressBars=this.$player.find(".progress_bars");this.$durationLabel=this.$player.find(".duration");this.$currentLabel=this.$player.find(".current_position");this.$toogleMute.click(c.proxy(this.toogleMute,this));this.$tooglePlay.click(c.proxy(this.tooglePlay,
this));this.$volBar.bind(mouseDownBind,c.proxy(this.volumeBarDown,this));this.$streamBar.click(c.proxy(this.progressBarClick,this));this.$progressBar.click(c.proxy(this.progressBarClick,this));this.$rightComp=this.$player.find(".component.right");c(window).resize(c.proxy(this.window_resize_timeout,this));a.bind("playerResize",c.proxy(this.windowResized,this));a.bind("playerResize",c.proxy(this.window_resize_timeout,this));this.windowResized();new e(this.$player.find(".song_artist"));new e(this.$player.find(".song_title"));
soundManager.onready(c.proxy(this.createSound,this))},this))};f.prototype={window_resize_timeout:function(){clearTimeout(this.resize_timeout);this.resize_timeout=setTimeout(d.proxy(this.windowResized,this),200)},windowResized:function(){var a=this.$player.width();this.$player.removeClass("stage1 stage2 stage3");450>a&&this.$player.addClass("stage1");390>a&&this.$player.addClass("stage2");330>a&&this.$player.addClass("stage3")},progressBarClick:function(a){if(1===this.sound.playState){var b,c;this.$player.hasClass("stage3")?
(b=this.$progressBars.eq(1).offset().left,c=this.$streamBar.eq(1).width()):(b=this.$progressBars.eq(0).offset().left,c=this.$streamBar.eq(0).width());this.sound.setPosition((a.pageX-b)/c*this.sound.duration)}return!1},volumeBarChange:function(a){0>a?a=0:50<a&&(a=50);a=Math.round(100*(a/50));this.sound.setVolume(a);this.sound.muted&&0<this.sound.volume?this.sound.unmute():this.sound.muted||0!=this.sound.volume||this.sound.mute();this.changeVolume(!1)},volumeBarDown:function(a){this.barPosition=this.$volBar.offset().left;
this.currentPosition=a.pageX;this.volumeBarChange(this.currentPosition-this.barPosition);d(document).bind(mouseMoveBind,d.proxy(this.volumeBarMove,this));d(document).bind(mouseUpBind,d.proxy(this.mouseUp,this));return!1},volumeBarMove:function(a){this.currentPosition=a.pageX;this.volumeBarChange(this.currentPosition-this.barPosition);return!1},mouseUp:function(){unbindMoveAndUp();return!1},stoppedSound:function(){this.changePlayingStatus()},whileloading:function(){this.$streamBar.css("width",100*
(this.sound.bytesLoaded/this.sound.bytesTotal)+"%");var a=Math.round(this.sound.duration/1E3),b=0;60<=a&&(b=Math.floor(a/60),a-=60*b);this.$durationLabel.text((10>b?"0"+b:b)+":"+(10>a?"0"+a:a))},whileplaying:function(){this.$progressBar.css("width",100*(this.sound.loaded?this.sound.position/this.sound.duration:this.sound.position/this.sound.durationEstimate)+"%");var a=Math.round(this.sound.position/1E3),b=0;60<=a&&(b=Math.floor(a/60),a-=60*b);this.$currentLabel.text((10>b?"0"+b:b)+":"+(10>a?"0"+
a:a));this.$player.is(":visible")||this.sound.destruct()},createSound:function(){var a="id"+Math.floor(99999*Math.random());this.$player.attr("id",a);this.sound=soundManager.createSound({id:a,url:this.url,autoLoad:!1,autoPlay:!1,onfinish:d.proxy(this.stoppedSound,this),whileloading:d.proxy(this.whileloading,this),whileplaying:d.proxy(this.whileplaying,this),volume:this.defaultVolume});this.changePlayingStatus();this.changeVolume()},changeVolume:function(a){var b=this.sound.muted?0:this.sound.volume,
c=200;!1===a&&(c=1);0==b?this.$toogleMute.addClass("muted"):(this.$toogleMute.removeClass("muted"),50>b?(this.$bar1.stop().fadeTo(c,b/50),this.$bar2.stop().fadeTo(c,0)):(this.$bar1.stop().fadeTo(c,1),this.$bar2.stop().fadeTo(c,(b-50)/50)));this.$volActiveBar.stop().animate({width:b+"%"},c)},toogleMute:function(){this.sound.toggleMute();this.sound.muted||0!=this.sound.volume||this.sound.setVolume(this.defaultVolume);this.changeVolume();return!1},tooglePlay:function(){this.sound.togglePause();this.changePlayingStatus();
return!1},changePlayingStatus:function(){this.sound.paused||0===this.sound.playState?this.$tooglePlay.removeClass("playing"):this.$tooglePlay.addClass("playing")}};return f});
