window.Modernizr=function(g,f,w){function s(a,b){return typeof a===b}function y(a,b){for(var c in a){var h=a[c];if(!~(""+h).indexOf("-")&&n[h]!==w)return"pfx"==b?h:!0}return!1}function p(a,b,c){var h=a.charAt(0).toUpperCase()+a.slice(1),d=(a+" "+E.join(h+" ")+h).split(" ");if(s(b,"string")||s(b,"undefined"))b=y(d,b);else a:{d=(a+" "+z.join(h+" ")+h).split(" "),a=d;for(var f in a)if(h=b[a[f]],h!==w){b=!1===c?a[f]:s(h,"function")?h.bind(c||b):h;break a}b=!1}return b}function L(){k.input=function(a){for(var b=
0,c=a.length;b<c;b++)A[a[b]]=a[b]in e;return A.list&&(A.list=!!f.createElement("datalist")&&!!g.HTMLDataListElement),A}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));k.inputtypes=function(a){for(var b=0,c,h,d,k=a.length;b<k;b++)e.setAttribute("type",h=a[b]),(c="text"!==e.type)&&(e.value=v,e.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(h)&&e.style.WebkitAppearance!==w?(q.appendChild(e),d=f.defaultView,c=d.getComputedStyle&&"textfield"!==
d.getComputedStyle(e,null).WebkitAppearance&&0!==e.offsetHeight,q.removeChild(e)):/^(search|tel)$/.test(h)||(/^(url|email)$/.test(h)?c=e.checkValidity&&!1===e.checkValidity():c=e.value!=v)),B[a[b]]=!!c;return B}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var k={},q=f.documentElement,d=f.createElement("modernizr"),n=d.style,e=f.createElement("input"),v=":)",u=" -webkit- -moz- -o- -ms- ".split(" "),E=["Webkit","Moz","O","ms"],z=["webkit","moz",
"o","ms"],d={},B={},A={},F=[],G=F.slice,C,x=function(a,b,c,h){var d,k,g,e,l=f.createElement("div"),r=f.body,m=r||f.createElement("body");if(parseInt(c,10))for(;c--;)g=f.createElement("div"),g.id=h?h[c]:"modernizr"+(c+1),l.appendChild(g);return d=['&#173;<style id="smodernizr">',a,"</style>"].join(""),l.id="modernizr",(r?l:m).innerHTML+=d,m.appendChild(l),r||(m.style.background="",m.style.overflow="hidden",e=q.style.overflow,q.style.overflow="hidden",q.appendChild(m)),k=b(l,a),r?l.parentNode.removeChild(l):
(m.parentNode.removeChild(m),q.style.overflow=e),!!k},J=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,c){c=c||f.createElement(a[b]||"div");b="on"+b;var h=b in c;return h||(c.setAttribute||(c=f.createElement("div")),c.setAttribute&&c.removeAttribute&&(c.setAttribute(b,""),h=s(c[b],"function"),s(c[b],"undefined")||(c[b]=w),c.removeAttribute(b))),h}}(),D={}.hasOwnProperty,t;s(D,"undefined")||s(D.call,"undefined")?t=function(a,
b){return b in a&&s(a.constructor.prototype[b],"undefined")}:t=function(a,b){return D.call(a,b)};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;var c=G.call(arguments,1),h=function(){if(this instanceof h){var d=function(){};d.prototype=b.prototype;var d=new d,f=b.apply(d,c.concat(G.call(arguments)));return Object(f)===f?f:d}return b.apply(a,c.concat(G.call(arguments)))};return h});d.flexbox=function(){return p("flexWrap")};d.flexboxlegacy=
function(){return p("boxDirection")};d.canvas=function(){var a=f.createElement("canvas");return!!a.getContext&&!!a.getContext("2d")};d.canvastext=function(){return!!k.canvas&&!!s(f.createElement("canvas").getContext("2d").fillText,"function")};d.touch=function(){var a;return"ontouchstart"in g||g.DocumentTouch&&f instanceof DocumentTouch?a=!0:x(["@media (",u.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),function(b){a=9===b.offsetTop}),a};d.postmessage=function(){return!!g.postMessage};
d.websqldatabase=function(){return!!g.openDatabase};d.indexedDB=function(){return!!p("indexedDB",g)};d.hashchange=function(){return J("hashchange",g)&&(f.documentMode===w||7<f.documentMode)};d.history=function(){return!!g.history&&!!history.pushState};d.draganddrop=function(){var a=f.createElement("div");return"draggable"in a||"ondragstart"in a&&"ondrop"in a};d.websockets=function(){return"WebSocket"in g||"MozWebSocket"in g};d.rgba=function(){n.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+
n.backgroundColor).indexOf("rgba")};d.hsla=function(){n.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+n.backgroundColor).indexOf("rgba")||!!~(""+n.backgroundColor).indexOf("hsla")};d.multiplebgs=function(){n.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(n.background)};d.backgroundsize=function(){return p("backgroundSize")};d.borderimage=function(){return p("borderImage")};d.borderradius=function(){return p("borderRadius")};d.boxshadow=
function(){return p("boxShadow")};d.textshadow=function(){return""===f.createElement("div").style.textShadow};d.opacity=function(){var a=u.join("opacity:.55;")+"";n.cssText=a;return/^0.55$/.test(n.opacity)};d.cssanimations=function(){return p("animationName")};d.csscolumns=function(){return p("columnCount")};d.cssgradients=function(){var a=("background-image:-webkit-gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:"+u.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,
-17);n.cssText=a;return!!~(""+n.backgroundImage).indexOf("gradient")};d.cssreflections=function(){return p("boxReflect")};d.csstransforms=function(){return!!p("transform")};d.csstransforms3d=function(){var a=!!p("perspective");return a&&"webkitPerspective"in q.style&&x("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b,c){a=9===b.offsetLeft&&3===b.offsetHeight}),a};d.csstransitions=function(){return p("transition")};d.fontface=function(){var a;
return x('@font-face {font-family:"font";src:url("https://")}',function(b,c){var h=f.getElementById("smodernizr"),h=(h=h.sheet||h.styleSheet)?h.cssRules&&h.cssRules[0]?h.cssRules[0].cssText:h.cssText||"":"";a=/src/i.test(h)&&0===h.indexOf(c.split(" ")[0])}),a};d.generatedcontent=function(){var a;return x(['#modernizr{font:0/0 a}#modernizr:after{content:"',v,'";visibility:hidden;font:3px/1 a}'].join(""),function(b){a=3<=b.offsetHeight}),a};d.video=function(){var a=f.createElement("video"),b=!1;try{if(b=
!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(c){}return b};d.audio=function(){var a=f.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,
""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(c){}return b};d.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(a){return!1}};d.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(a){return!1}};d.webworkers=function(){return!!g.Worker};d.applicationcache=function(){return!!g.applicationCache};
for(var H in d)t(d,H)&&(C=H.toLowerCase(),k[C]=d[H](),F.push((k[C]?"":"no-")+C));k.input||L();k.addTest=function(a,b){if("object"==typeof a)for(var c in a)t(a,c)&&k.addTest(c,a[c]);else{a=a.toLowerCase();if(k[a]!==w)return k;b="function"==typeof b?b():b;q.className+=" "+(b?"":"no-")+a;k[a]=b}return k};n.cssText="";return d=e=null,function(a,b){function c(){var c=K.elements;return"string"==typeof c?c.split(" "):c}function h(c){var b=n[c[e]];return b||(b={},p++,c[e]=p,n[p]=b),b}function d(c,a,m){a||
(a=b);if(I)return a.createElement(c);m||(m=h(a));var f;return m.cache[c]?f=m.cache[c].cloneNode():r.test(c)?f=(m.cache[c]=m.createElem(c)).cloneNode():f=m.createElem(c),f.canHaveChildren&&!l.test(c)?m.frag.appendChild(f):f}function f(b,a){a.cache||(a.cache={},a.createElem=b.createElement,a.createFrag=b.createDocumentFragment,a.frag=a.createFrag());b.createElement=function(c){return K.shivMethods?d(c,b,a):a.createElem(c)};b.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+
c().join().replace(/\w+/g,function(c){return a.createElem(c),a.frag.createElement(c),'c("'+c+'")'})+");return n}")(K,a.frag)}function k(c){c||(c=b);var a=h(c);if(K.shivCSS&&!m&&!a.hasCSS){var d,r=c;d=r.createElement("p");r=r.getElementsByTagName("head")[0]||r.documentElement;d=(d.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>",r.insertBefore(d.lastChild,r.firstChild));a.hasCSS=!!d}return I||f(c,a),c}var g=
a.html5||{},l=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,r=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,m,e="_html5shiv",p=0,n={},I;(function(){try{var c=b.createElement("a");c.innerHTML="<xyz></xyz>";m="hidden"in c;var a;if(!(a=1==c.childNodes.length)){b.createElement("a");var h=b.createDocumentFragment();a="undefined"==typeof h.cloneNode||"undefined"==typeof h.createDocumentFragment||"undefined"==typeof h.createElement}I=
a}catch(d){I=m=!0}})();var K={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==g.shivCSS,supportsUnknownElements:I,shivMethods:!1!==g.shivMethods,type:"default",shivDocument:k,createElement:d,createDocumentFragment:function(a,d){a||(a=b);if(I)return a.createDocumentFragment();d=d||h(a);for(var m=d.frag.cloneNode(),f=0,r=c(),k=r.length;f<k;f++)m.createElement(r[f]);
return m}};a.html5=K;k(b)}(this,f),k._version="2.6.2",k._prefixes=u,k._domPrefixes=z,k._cssomPrefixes=E,k.mq=function(a){var b=g.matchMedia||g.msMatchMedia;if(b)return b(a).matches;var c;return x("@media "+a+" { #modernizr { position: absolute; } }",function(a){c="absolute"==(g.getComputedStyle?getComputedStyle(a,null):a.currentStyle).position}),c},k.hasEvent=J,k.testProp=function(a){return y([a])},k.testAllProps=p,k.testStyles=x,q.className=q.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+
F.join(" ")),k}(this,this.document);
(function(g,f,w){function s(c){return"[object Function]"==E.call(c)}function y(c){return"string"==typeof c}function p(){}function L(c){return!c||"loaded"==c||"complete"==c||"uninitialized"==c}function k(){var c=z.shift();B=1;c?c.t?v(function(){("c"==c.t?b.injectCss:b.injectJs)(c.s,0,c.a,c.x,c.e,1)},0):(c(),k()):B=0}function q(c,a,d,g,e,p,l){function r(b){if(!n&&L(m.readyState)&&(q.r=n=1,!B&&k(),m.onload=m.onreadystatechange=null,b)){"img"!=c&&v(function(){G.removeChild(m)},50);for(var d in t[a])t[a].hasOwnProperty(d)&&
t[a][d].onload()}}l=l||b.errorTimeout;var m=f.createElement(c),n=0,s=0,q={t:d,s:a,e:e,a:p,x:l};1===t[a]&&(s=1,t[a]=[]);"object"==c?m.data=a:(m.src=a,m.type=c);m.width=m.height="0";m.onerror=m.onload=m.onreadystatechange=function(){r.call(this,s)};z.splice(g,0,q);"img"!=c&&(s||2===t[a]?(G.insertBefore(m,F?null:u),v(r,l)):t[a].push(m))}function d(a,b,d,f,g){return B=0,b=b||"j",y(a)?q("c"==b?x:C,a,b,this.i++,d,f,g):(z.splice(this.i++,0,a),1==z.length&&k()),this}function n(){var a=b;return a.loader={load:d,
i:0},a}var e=f.documentElement,v=g.setTimeout,u=f.getElementsByTagName("script")[0],E={}.toString,z=[],B=0,A="MozAppearance"in e.style,F=A&&!!f.createRange().compareNode,G=F?e:u.parentNode,e=g.opera&&"[object Opera]"==E.call(g.opera),e=!!f.attachEvent&&!e,C=A?"object":e?"script":"img",x=e?"script":C,J=Array.isArray||function(a){return"[object Array]"==E.call(a)},D=[],t={},H={timeout:function(a,b){return b.length&&(a.timeout=b[0]),a}},a,b;b=function(a){function d(a){a=a.split("!");var b=D.length,c=
a.pop(),f=a.length,c={url:c,origUrl:c,prefixes:a},h,k,g;for(k=0;k<f;k++)g=a[k].split("="),(h=H[g.shift()])&&(c=h(c,g));for(k=0;k<b;k++)c=D[k](c);return c}function f(a,c,b,k,g){var e=d(a),l=e.autoCallback;e.url.split(".").pop().split("?").shift();e.bypass||(c&&(c=s(c)?c:c[a]||c[k]||c[a.split("/").pop().split("?")[0]]),e.instead?e.instead(a,c,b,k,g):(t[e.url]?e.noexec=!0:t[e.url]=1,b.load(e.url,e.forceCSS||!e.forceJS&&"css"==e.url.split(".").pop().split("?").shift()?"c":w,e.noexec,e.attrs,e.timeout),
(s(c)||s(l))&&b.load(function(){n();c&&c(e.origUrl,g,k);l&&l(e.origUrl,g,k);t[e.url]=2})))}function k(a,c){function b(a,h){if(a)if(y(a))h||(e=function(){var a=[].slice.call(arguments);g.apply(this,a);l()}),f(a,e,c,0,d);else{if(Object(a)===a)for(q in n=function(){var c=0,b;for(b in a)a.hasOwnProperty(b)&&c++;return c}(),a)a.hasOwnProperty(q)&&(!h&&!--n&&(s(e)?e=function(){var a=[].slice.call(arguments);g.apply(this,a);l()}:e[q]=function(a){return function(){var c=[].slice.call(arguments);a&&a.apply(this,
c);l()}}(g[q])),f(a[q],e,c,q,d))}else!h&&l()}var d=!!a.test,h=a.load||a.both,e=a.callback||p,g=e,l=a.complete||p,n,q;b(d?a.yep:a.nope,!!h);h&&b(h)}var g,e,l=this.yepnope.loader;if(y(a))f(a,0,l,0);else if(J(a))for(g=0;g<a.length;g++)e=a[g],y(e)?f(e,0,l,0):J(e)?b(e):Object(e)===e&&k(e,l);else Object(a)===a&&k(a,l)};b.addPrefix=function(a,b){H[a]=b};b.addFilter=function(a){D.push(a)};b.errorTimeout=1E4;null==f.readyState&&f.addEventListener&&(f.readyState="loading",f.addEventListener("DOMContentLoaded",
a=function(){f.removeEventListener("DOMContentLoaded",a,0);f.readyState="complete"},0));g.yepnope=n();g.yepnope.executeStack=k;g.yepnope.injectJs=function(a,d,e,g,n,q){var l=f.createElement("script"),r,m;g=g||b.errorTimeout;l.src=a;for(m in e)l.setAttribute(m,e[m]);d=q?k:d||p;l.onreadystatechange=l.onload=function(){!r&&L(l.readyState)&&(r=1,d(),l.onload=l.onreadystatechange=null)};v(function(){r||(r=1,d(1))},g);n?l.onload():u.parentNode.insertBefore(l,u)};g.yepnope.injectCss=function(a,b,d,e,g,n){e=
f.createElement("link");var l;b=n?k:b||p;e.href=a;e.rel="stylesheet";e.type="text/css";for(l in d)e.setAttribute(l,d[l]);g||(u.parentNode.insertBefore(e,u),v(b,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
