define(["jquery","utils/utils"],function(a){var f=function(b,d,c,e,f,g){this.$target=b;this.enabled=!1;this.dragable=f;this.preserveRatio=g;void 0==this.preserveRatio&&(this.preserveRatio=!0);this.$holder=a('<div class="scalable_holder"></div>').appendTo(this.$target);this.left=parseInt(b.css("left"),10);this.top=parseInt(b.css("top"),10);this.width=b.width();this.height=b.height();this.ratio=this.width/this.height;WP_DEBUG&&console.log(this.width);this.minHeight=this.minWidth=5;this.horizontal=c;
this.vertical=e;f&&(this.$dragArea=a('<div class="dragArea grabhand"></div>').appendTo(this.$holder),this.$dragArea.bind(mouseDownBind,a.proxy(this.dragDown,this)));c&&!e?this.$holder.append(a('<div class="scale_button"></div>').css({left:"0%",top:"50%"}).attr("rel","cl").bind(mouseDownBind,a.proxy(this.scaleDown,this))).append(a('<div class="scale_button"></div>').css({left:"100%",top:"50%"}).attr("rel","cr").bind(mouseDownBind,a.proxy(this.scaleDown,this))):!c&&e?this.$holder.append(a('<div class="scale_button"></div>').css({left:"0%",
top:"50%"}).attr("rel","ct").bind(mouseDownBind,a.proxy(this.scaleDown,this))).append(a('<div class="scale_button"></div>').css({left:"100%",top:"50%"}).attr("rel","cb").bind(mouseDownBind,a.proxy(this.scaleDown,this))):this.$holder.append(a('<div class="scale_button"></div>').css({left:"0",top:"0"}).attr("rel","lt").bind(mouseDownBind,a.proxy(this.scaleDown,this))).append(a('<div class="scale_button"></div>').css({left:"100%",top:"0"}).attr("rel","rt").bind(mouseDownBind,a.proxy(this.scaleDown,this))).append(a('<div class="scale_button"></div>').css({left:"0%",
top:"100%"}).attr("rel","lb").bind(mouseDownBind,a.proxy(this.scaleDown,this))).append(a('<div class="scale_button"></div>').css({left:"100%",top:"100%"}).attr("rel","rb").bind(mouseDownBind,a.proxy(this.scaleDown,this)));this.$dragElements=[];this.$dragElements.push(this.$dragArea);this.$scaleButtons=this.$holder.find(".scale_button");this.enabled||this.$holder.css("display","none")};f.prototype={enable:function(){this.$holder.css("display","block");this.enabled=!0;this.rebind()},disable:function(){this.$holder.css("display",
"none");this.enabled=!1},rebind:function(){this.dragable&&(this.$dragArea.unbind(mouseDownBind),this.$dragArea.bind(mouseDownBind,a.proxy(this.dragDown,this)));this.$scaleButtons.unbind(mouseDownBind);this.$scaleButtons.bind(mouseDownBind,a.proxy(this.scaleDown,this))},addDragger:function(b){b.addClass("grabhand").bind(mouseDownBind,a.proxy(this.dragDown,this));this.$dragElements.push(b)},scaleDown:function(b){this.enabled&&(this.rel=a(b.target).attr("rel"),this.iniX=b.pageX,this.iniY=b.pageY,this.left=
parseInt(this.$target.css("left"),10),this.top=parseInt(this.$target.css("top"),10),this.width=this.$target.width(),this.height=this.$target.height(),a(document).bind(mouseMoveBind,a.proxy(this.scaleMove,this)),a(document).bind(mouseUpBind,a.proxy(this.scaleUp,this)));return!1},scaleMove:function(a){var d=a.pageX-this.iniX,c=a.pageY-this.iniY;this.horizontal&&!this.vertical&&("cl"==this.rel?(this.left+=d,this.width-=d):this.width+=d,this.width<this.minWidth&&("cl"==this.rel&&(this.left-=this.minWidth-
this.width),this.width=this.minWidth));!this.horizontal&&this.vertical&&("cb"==this.rel?(this.top+=c,this.height-=c):this.height+=c,this.height<this.minHeight&&("cb"==this.rel&&(this.top-=this.minHeight-this.height),this.height=this.minHeight));this.horizontal&&this.vertical&&("l"==this.rel.charAt(0)?(this.left+=d,this.width-=d):this.width+=d,"t"==this.rel.charAt(1)?(this.top+=c,this.height-=c):this.height+=c,this.width<this.minWidth&&("l"==this.rel.charAt(0)&&(this.left-=this.minWidth-this.width),
this.width=this.minWidth),this.preserveRatio&&this.width/this.height!=this.ratio&&(d=this.height-this.width/this.ratio,"t"==this.rel.charAt(1)&&(this.top+=d),this.height=this.width/this.ratio));this.iniX=a.pageX;this.iniY=a.pageY;this.update();return!1},scaleUp:function(){unbindMoveAndUp();return!1},dragDown:function(b){this.enabled&&(this.currX=b.pageX,this.currY=b.pageY,this.left=parseInt(this.$target.css("left"),10),this.top=parseInt(this.$target.css("top"),10),this.width=this.$target.width(),
this.height=this.$target.height(),a.each(this.$dragElements,function(b,c){a(c).addClass("down")}),a(document).bind(mouseMoveBind,a.proxy(this.dragMove,this)),a(document).bind(mouseUpBind,a.proxy(this.dragUp,this)));return!1},dragMove:function(a){var d=a.pageX;a=a.pageY;this.left+=d-this.currX;this.top+=a-this.currY;this.currX=d;this.currY=a;this.update();return!1},dragUp:function(b){unbindMoveAndUp();a.each(this.$dragElements,function(b,c){a(c).removeClass("down")});return!1},update:function(){var a=
Math.round(this.left),d=Math.round(this.top),c=this.width,e=this.height;this.$target.css({left:a+"px",top:d+"px"});this.horizontal&&this.$target.css({width:c+"px"});this.vertical&&this.$target.css({height:e+"px"});this.$target.trigger("change",{left:a,top:d,width:c,height:e})},change:function(){}};return f});
