define(["jquery","ui-elements","libraries/inheritance"],function(c,q){var p=Class.extend({generalInit:function(a,b,h,d){this.depth=a;this.appended=this.removed=!1;this.$elements=b;this.$element=c('<div class="slide_element grabhand"></div>').append(this.$content);this.currentInstance=2;this.parameters={type:this.type,xpos1:0,xpos2:0,xpos3:0,xpos4:0,ypos1:0,ypos2:0,ypos3:0,ypos4:0,opc1:100,opc2:100,opc3:100,opc4:100,size1:100,size2:100,size3:100,size4:100,duration1:0.5,duration2:0.5,duration3:0.5,
delay1:0,delay2:0,delay3:0,ease1:"easeOut",ease2:"easeOut",ease3:"easeOut",type1:"Expo",type2:"Expo",type3:"Expo",iniWidth:100,iniHeight:0,vertical_snapping:"center",horizontal_snapping:"center",min_scale:0,max_scale:999};"image"==this.type&&(this.parameters.iniWidth=this.iniWidth,this.parameters.iniHeight=this.iniHeight);void 0!=d&&c.each(d,c.proxy(function(a,b){this.parameters.hasOwnProperty(a)&&(this.parameters[a]=b)},this));"image"==this.type&&(this.width=this.iniWidth*(this.parameters["size"+
this.currentInstance]/100),this.height=this.iniHeight*(this.parameters["size"+this.currentInstance]/100));!0!=h&&void 0!=h||this.createElement();this.updateInstance()},updateInsideContent:function(a){this.$content.remove();this.$content=a.unbind("click").removeClass("button_preview").attr("id","");this.$element.prepend(this.$content)},createElement:function(a){if(!this.removed){this.selected=!1;this.$offLimits=c('<a class="off_limits" href="#"></a>');this.appendElement();if(a||void 0==a)"image"!=
this.type?(this.width=this.parameters.iniWidth,this.$element.css({width:this.width+"px"})):this.$element.css({width:this.width+"px",height:this.height+"px"});this.elementsWidth=this.$elements.width();this.elementsHeight=this.$elements.height();this.updatePosition();this.created=!0;this.overBoards=!1;"image"==this.type?(this.$content.css({width:"100%",height:"100%"}),this.scale=new q.RelativeScalable(this.$element,!1,!0,!0,!0,!0)):this.scale=new q.RelativeScalable(this.$element,!1,!0,!1,!0,!1);this.scale.addDragger(this.$offLimits);
return!1}},appendElement:function(){this.removed||(this.appended?this.$element.stop().show():(this.appended=!0,this.$element.appendTo(this.$elements),this.$offLimits.appendTo(this.$elements),this.$elements.bind("instanceChange",c.proxy(this.changeInstance,this)),preventDragDefault(this.$element),this.$element.click(c.proxy(this.selectElement,this)),this.$element.css("cursor","pointer"),preventDragDefault(this.$offLimits),this.$offLimits.click(c.proxy(this.selectElement,this)),this.$offLimits.css("cursor",
"pointer"),"image"==this.type?(this.$element.unbind("change"),this.$element.bind("change",c.proxy(this.onImageResize,this))):(this.$element.unbind("change"),this.$element.bind("change",c.proxy(this.onOtherResize,this))),this.updateDepth(),this.updatePosition()))},updateDepth:function(){this.$element.css("z-index",this.depth)},setDepth:function(a){this.depth=a;this.updateDepth()},updatePosition:function(a){var b=this.parameters["ypos"+this.currentInstance],h=this.parameters["xpos"+this.currentInstance];
void 0==a&&(a=!1);b={top:b+"px",left:h+"px",opacity:1};"image"==this.type?(b.width=this.iniWidth*(this.parameters["size"+this.currentInstance]/100)+"px",b.height=this.iniHeight*(this.parameters["size"+this.currentInstance]/100)+"px"):b.width=this.iniWidth+"px";console.log(b);a?this.$element.stop().animate(b,200):this.$element.stop().css(b);this.created&&("image"==this.type&&(this.parameters["size"+this.currentInstance]=Math.round(1E3*(this.width/this.iniWidth))/10),c(this).trigger("changePos"),this.checkOverflow())},
checkOverflow:function(){var a=this.width,b=this.height,h=this.parameters["ypos"+this.currentInstance],d=this.parameters["xpos"+this.currentInstance],e=d>this.elementsWidth,l=d<0-a,m=h<0-b,n=h>this.elementsHeight;if(e||l||m||n){var f=0,g=0,k="off_bottom";m&&l?k="off_lt":m&&e?(k="off_rt",f=this.elementsWidth-54):n&&l?(k="off_lb",g=this.elementsHeight-54):n&&e?(k="off_rb",f=this.elementsWidth-54,g=this.elementsHeight-54):n?(k="off_bottom",g=this.elementsHeight-54,f=d+a/2-27):m?(k="off_top",f=d+a/2-
27):l?(k="off_left",g=h+b/2-27):e&&(k="off_right",f=this.elementsWidth-54,g=h+b/2-27);m?this.$element.css("top",-b-7+"px"):n&&this.$element.css("top",this.elementsHeight+3+"px");l?this.$element.css("left",-a-6+"px"):e&&this.$element.css("left",this.elementsWidth+3+"px");0>g?g=0:g>this.elementsHeight-54&&(g=this.elementsHeight-54);0>f?f=0:f>this.elementsWidth-54&&(f=this.elementsWidth-54);this.$offLimits.css({top:g,left:f}).removeClass("off_lt off_rt off_lb off_rb off_bottom off_top off_left off_right").addClass(k);
this.overBoards||(this.$offLimits.stop().css("display","block").fadeTo(200,1),this.overBoards=!0)}else this.overBoards&&(this.$offLimits.stop().fadeTo(200,0,function(){c(this).css("display","none")}),this.overBoards=!1)},getInstance:function(a){a++;var b={};b.x=this.parameters["xpos"+a];b.y=this.parameters["ypos"+a];b.opacity=this.parameters["opc"+a];"image"==this.type&&(b.size=this.parameters["size"+a]);return b},getAnimationInstance:function(a){a++;var b={};b.delay=this.parameters["delay"+a];b.duration=
this.parameters["duration"+a];b.ease=this.parameters["ease"+a];b.type=this.parameters["type"+a];return b},setInstance:function(a,b){a++;this.currentInstance=a;this.parameters["xpos"+this.currentInstance]=parseInt(b.x,10);this.parameters["ypos"+this.currentInstance]=parseInt(b.y,10);this.parameters["opc"+this.currentInstance]=parseFloat(b.opacity,10);"image"==this.type&&(this.parameters["size"+this.currentInstance]=parseFloat(b.size,10),this.width=parseFloat(b.size,10)/100*this.iniWidth,this.height=
parseFloat(b.size,10)/100*this.iniHeight);this.updateInstance()},onImageResize:function(a,b){this.width=b.width;this.height=b.height;this.parameters["xpos"+this.currentInstance]=b.left;this.parameters["ypos"+this.currentInstance]=b.top;this.updatePosition(!1)},onOtherResize:function(a,b){this.width=b.width;this.parameters.iniWidth=this.width;this.parameters["ypos"+this.currentInstance]=b.top;this.parameters["xpos"+this.currentInstance]=b.left;this.updatePosition(!1)},setAnimationInstance:function(a,
b){a++;this.parameters["delay"+a]=b.delay;this.parameters["duration"+a]=b.duration;this.parameters["ease"+a]=b.ease;this.parameters["type"+a]=b.type},matchPrevious:function(){0!=this.currentInstance&&(this.parameters["xpos"+this.currentInstance]=this.parameters["xpos"+(this.currentInstance-1)],this.parameters["ypos"+this.currentInstance]=this.parameters["ypos"+(this.currentInstance-1)],this.updateInstance())},matchFollowing:function(){4!=this.currentInstance&&(this.parameters["xpos"+this.currentInstance]=
this.parameters["xpos"+(this.currentInstance+1)],this.parameters["ypos"+this.currentInstance]=this.parameters["ypos"+(this.currentInstance+1)],this.updateInstance())},snapTo:function(a){var b=0,c=0;"image"!=this.type&&(this.height=this.$element.height());console.log(this.elementsWidth);console.log(this.width);switch(a.charAt(0)){case "l":c=0;break;case "c":c=this.elementsWidth/2-this.width/2;break;case "r":c=this.elementsWidth-this.width}switch(a.charAt(1)){case "t":b=0;break;case "c":b=this.elementsHeight/
2-this.height/2;break;case "b":b=this.elementsHeight-this.height}this.parameters["xpos"+this.currentInstance]=Math.round(c);this.parameters["ypos"+this.currentInstance]=Math.round(b);this.updateInstance()},changeInstance:function(a){this.currentInstance=a;this.updateInstance()},updateInstance:function(){if("image"==this.type){var a=this.iniHeight*(this.parameters["size"+this.currentInstance]/100);this.width=this.iniWidth*(this.parameters["size"+this.currentInstance]/100);this.height=a}a=this.parameters["opc"+
this.currentInstance]/100;this.$content.stop().fadeTo(200,a);this.updatePosition(!0)},selectElement:function(a){this.selected||(this.selected=!0,this.$offLimits.css({border:"2px solid #FFFF00","margin-left":"-2px","margin-top":"-2px"}),this.scale.enable(),this.$elements.bind(mouseDownBind,c.proxy(this.unselectElement,this)),!1!==a&&this.$elements.trigger("elementSelected",this),this.$element.css("cursor",""),this.$offLimits.css("cursor",""),c("body").keydown(c.proxy(this.keyDownHandler,this)))},keyDownHandler:function(a){switch(a.which){case 37:this.parameters["xpos"+
this.currentInstance]--;this.updatePosition();a.preventDefault();break;case 38:this.parameters["ypos"+this.currentInstance]--;this.updatePosition();a.preventDefault();break;case 39:this.parameters["xpos"+this.currentInstance]++;this.updatePosition();a.preventDefault();break;case 40:this.parameters["ypos"+this.currentInstance]++,this.updatePosition(),a.preventDefault()}},unselectElement:function(a){var b=c(a.target);c(a.target).get(0)!==this.$element.get(0)&&0==this.$element.has(b).length&&this.unselectElem()},
unselectElem:function(){this.selected&&(this.$offLimits.css({border:"0px solid #A9A801","margin-left":"0px","margin-top":"0px"}),this.scale.disable(),this.$elements.trigger("elementUnselect",this),this.selected=!1,this.$element.css("cursor","pointer"),this.$offLimits.css("cursor","pointer"),c("body").unbind("keydown"))},remove:function(){this.$element.stop().hide();this.$offLimits.stop().hide()},deleteElement:function(a){this.removed=!0;this.$element.stop().fadeTo(200,0,function(){c(this).remove()});
this.$offLimits.stop().fadeTo(200,0,function(){c(this).remove()});this.appended=!1;a&&c("#slider_elements_overview_orderable_list").trigger("removeItem",[this.depth])},setSpecificValues:function(a){this.$element.css({width:"auto",overflow:"hidden !important",top:0,left:0,bottom:"auto",right:"auto"});this.width=this.$element.width();this.height=this.$element.height();"image"!=this.type&&(this.parameters.iniWidth=this.width,this.parameters.iniHeight=this.height);this.$element.css({width:this.width+
"px",height:this.height+"px",overflow:"visible"});this.updatePosition(!1)},getSpecificValues:function(){return this.specifics},val:function(){if(this.removed)return"";var a=JSON.stringify(this.parameters),a=c("<div></div>").append(this.$content).attr("rel",a);return c("<div></div>").append(a).html()}}),r=p.extend({init:function(a,b,c,d,e){this.$content=c.removeClass("button_preview").attr("id","").addClass("pq_button");this.type="button";this.generalInit(a,b,d,e)}}),s=p.extend({init:function(a,b,
c,d,e){this.$content=c.removeClass("button_preview").attr("id","");this.type="text";this.generalInit(a,b,d,e)}});return{ImageElement:p.extend({init:function(a,b,c,d,e,l,m){this.$content=c;this.width=d;this.height=e;this.iniWidth=d;this.iniHeight=e;this.type="image";this.generalInit(a,b,l,m)}}),TextElement:s,ButtonElement:r}});
